config/routes.rb
Rails.application.routes.draw do
  root "application#index"
  get "service-worker.js", to: "application#serviceworker", as: "serviceworker"
  get "/up", to: "application#up", as: "up"
  get "cacheclear", to: "application#cacheclear", as: "cacheclear"
  get "jobsrun", to: "application#jobsrun", as: "jobsrun"

  # Authentication
  get "authentication/login", to: "authentication#login", as: "authentication_login"
  get "authentication/recover-password", to: "authentication#recover_password", as: "authentication_recover_password"
  get "authentication/update-password/:id", to: "authentication#update_password", as: "authentication_update_password"
  post "authentication/login-action", to: "authentication#login_action", as: "authentication_login_action"
  post "authentication/recover-password-action", to: "authentication#recover_password_action", as: "authentication_recover_password_action"
  post "authentication/update-password-action/:id", to: "authentication#update_password_action", as: "authentication_update_password_action"
  get "authentication/logout", to: "authentication#logout", as: "authentication_logout"
  get "authentication/first-run", to: "authentication#first_run", as: "authentication_first_run"
  post "authentication/first-run-action", to: "authentication#first_run_action", as: "authentication_first_run_action"

  # User
  get "users", to: "users#index", as: "users"
  get "users/show/:id", to: "users#show", as: "users_show"
  get "users/actions/:type", to: "users#actions", as: "users_actions"
  get "users/actions/:type/:id", to: "users#actions", as: "users_actions_id"
  post "users/create-action", to: "users#create_action", as: "users_create_action"
  post "users/edit-action/:id", to: "users#edit_action", as: "users_edit_action"
  post "users/edit-policies-action/:id", to: "users#edit_policies_action", as: "users_edit_policies_action"
  post "users/regenerate-password-action/:id", to: "users#regenerate_password_action", as: "users_regenerate_password_action"
  post "users/destroy-action/:id", to: "users#destroy_action", as: "users_destroy_action"
  post "users/toggle-prefer-action", to: "users#toggle_prefer_action", as: "users_toggle_prefer_action"

  # Project
  get "projects", to: "projects#index", as: "projects"
  get "projects/show/:id", to: "projects#show", as: "projects_show"
  get "projects/show-attachment/:id", to: "projects#show_attachment", as: "projects_show_attachment"
  get "projects/show-log/:id", to: "projects#show_log", as: "projects_show_log"
  get "projects/actions/:type", to: "projects#actions", as: "projects_actions"
  get "projects/actions/:type/:id", to: "projects#actions", as: "projects_actions_id"
  post "projects/create-action", to: "projects#create_action", as: "projects_create_action"
  post "projects/edit-action/:id", to: "projects#edit_action", as: "projects_edit_action"
  post "projects/archive-action/:id", to: "projects#archive_action", as: "projects_archive_action"
  post "projects/unarchive-action/:id", to: "projects#unarchive_action", as: "projects_unarchive_action"
  post "projects/destroy-action/:id", to: "projects#destroy_action", as: "projects_destroy_action"
  post "projects/add-procedure-action/:id", to: "projects#add_procedure_action", as: "projects_add_procedure_action"
  post "projects/add-procedures-item-action/:id", to: "projects#add_procedures_item_action", as: "projects_add_procedures_item_action"
  post "projects/add-member-action/:id", to: "projects#add_member_action", as: "projects_add_member_action"
  post "projects/edit-member-action/:id/:member_id", to: "projects#edit_member_action", as: "projects_edit_member_action"
  post "projects/remove-member-action/:id/:member_id", to: "projects#remove_member_action", as: "projects_remove_member_action"
  post "projects/add-log-action/:id", to: "projects#add_log_action", as: "projects_add_log_action"
  post "projects/edit-log-action/:id/:log_id", to: "projects#edit_log_action", as: "projects_edit_log_action"
  post "projects/share-log-action/:id/:log_id", to: "projects#share_log_action", as: "projects_share_log_action"
  post "projects/unshare-log-action/:id/:log_id", to: "projects#unshare_log_action", as: "projects_unshare_log_action"
  post "projects/remove-log-action/:id/:log_id", to: "projects#remove_log_action", as: "projects_remove_log_action"
  post "projects/add-attachment-action/:id", to: "projects#add_attachment_action", as: "projects_add_attachment_action"
  post "projects/edit-attachment-action/:id/:attachment_id", to: "projects#edit_attachment_action", as: "projects_edit_attachment_action"
  post "projects/remove-attachment-action/:id/:attachment_id", to: "projects#remove_attachment_action", as: "projects_remove_attachment_action"
  get "projects/:folder_id", to: "projects#index", as: "projects_for_folder"

  # Procedure
  get "procedures", to: "procedures#index", as: "procedures"
  get "procedures/show/:id", to: "procedures#show", as: "procedures_show"
  get "procedures/actions/:type", to: "procedures#actions", as: "procedures_actions"
  get "procedures/actions/:type/:id", to: "procedures#actions", as: "procedures_actions_id"
  post "procedures/create-action", to: "procedures#create_action", as: "procedures_create_action"
  post "procedures/edit-action/:id", to: "procedures#edit_action", as: "procedures_edit_action"
  post "procedures/archive-action/:id", to: "procedures#archive_action", as: "procedures_archive_action"
  post "procedures/unarchive-action/:id", to: "procedures#unarchive_action", as: "procedures_unarchive_action"
  post "procedures/toggle-show-archived-projects-action/:id", to: "procedures#toggle_show_archived_projects_action", as: "procedures_toggle_show_archived_projects_action"
  post "procedures/remove-archived-projects-action/:id", to: "procedures#remove_archived_projects_action", as: "procedures_remove_archived_projects_action"
  post "procedures/clone-action/:id", to: "procedures#clone_action", as: "procedures_clone_action"
  post "procedures/destroy-action/:id", to: "procedures#destroy_action", as: "procedures_destroy_action"
  post "procedures/add-status-action/:id", to: "procedures#add_status_action", as: "procedures_add_status_action"
  post "procedures/edit-status-action/:id/:status_id", to: "procedures#edit_status_action", as: "procedures_edit_status_action"
  post "procedures/edit-status-assignments-action/:id/:status_id", to: "procedures#edit_status_assignments_action", as: "procedures_edit_status_assignments_action"
  post "procedures/remove-status-action/:id/:status_id", to: "procedures#remove_status_action", as: "procedures_remove_status_action"
  post "procedures/move-status-action/:id/:status_id", to: "procedures#move_status_action", as: "procedures_move_status_action"
  post "procedures/toggle-status-automation-action/:id/:status_id", to: "procedures#toggle_status_automation_action", as: "procedures_toggle_status_automation_action"
  post "procedures/take-tasks-to-status-action/:id/:status_id", to: "procedures#take_tasks_to_status_action", as: "procedures_take_tasks_to_status_action"
  post "procedures/add-item-action/:id", to: "procedures#add_item_action", as: "procedures_add_item_action"
  post "procedures/edit-item-action/:id/:item_id", to: "procedures#edit_item_action", as: "procedures_edit_item_action"
  post "procedures/remove-item-action/:id/:item_id", to: "procedures#remove_item_action", as: "procedures_remove_item_action"
  post "procedures/move-item-action/:id/:item_id", to: "procedures#move_item_action", as: "procedures_move_item_action"

  # Posts
  get "posts", to: "posts#index", as: "posts"
  get "posts/actions/:type", to: "posts#actions", as: "posts_actions"
  post "posts/create-action", to: "posts#create_action", as: "posts_create_action"
  post "posts/edit-action/:id", to: "posts#edit_action", as: "posts_edit_action"
  post "posts/destroy-action/:id", to: "posts#destroy_action", as: "posts_destroy_action"

  # Presentation
  get "presentations", to: "presentations#index", as: "presentations"
  get "presentations/show/:id", to: "presentations#show", as: "presentations_show"
  get "presentations/player/:id", to: "presentations#player", as: "presentations_player"
  get "presentations/actions/:type", to: "presentations#actions", as: "presentations_actions"
  get "presentations/actions/:type/:id", to: "presentations#actions", as: "presentations_actions_id"
  post "presentations/create-action", to: "presentations#create_action", as: "presentations_create_action"
  post "presentations/edit-action/:id", to: "presentations#edit_action", as: "presentations_edit_action"
  post "presentations/import-action/:id", to: "presentations#import_action", as: "presentations_import_action"
  post "presentations/destroy-action/:id", to: "presentations#destroy_action", as: "presentations_destroy_action"
  post "presentations/share-action/:id", to: "presentations#share_action", as: "presentations_share_action"
  post "presentations/unshare-action/:id", to: "presentations#unshare_action", as: "presentations_unshare_action"
  post "presentations/add-page-action/:id", to: "presentations#add_page_action", as: "presentations_add_page_action"
  post "presentations/edit-page-action/:id/:page_id", to: "presentations#edit_page_action", as: "presentations_edit_page_action"
  post "presentations/remove-page-action/:id/:page_id", to: "presentations#remove_page_action", as: "presentations_remove_page_action"
  post "presentations/move-page-action/:id/:page_id", to: "presentations#move_page_action", as: "presentations_move_page_action"
  post "presentations/add-action-action/:id", to: "presentations#add_action_action", as: "presentations_add_action_action"
  post "presentations/remove-action-action/:id", to: "presentations#remove_action_action", as: "presentations_remove_action_action"
  post "presentations/add-note-action/:id", to: "presentations#add_note_action", as: "presentations_add_note_action"

app/models/project.rb
class Project < ApplicationRecord
  include ActionView::RecordIdentifier
  include Cachable
  include UserPreferrable
  include Folderable
  include AlghoritmicOrderable

  enum :archived_reason, {
    other: 0,
    completed: 1,
    not_started: 2,
    blocked_by_other: 3,
    blocked_by_me: 4
  }

  # RELATIONS
  ############################################################

  has_many :projects_members, dependent: :destroy, class_name: "Projects::Member"
  has_many :projects_logs, dependent: :destroy, class_name: "Projects::Log"
  has_many :projects_attachments, dependent: :destroy, class_name: "Projects::Attachment"
  has_many :projects_events, dependent: :destroy, class_name: "Projects::Event"

  has_many :procedures_items, as: :resource, dependent: :destroy, class_name: "Procedures::Item"
  has_many :procedures_as_item, through: :procedures_items, source: :procedure

  has_many :procedures, dependent: :destroy
  has_many :tasks, dependent: :destroy

  has_many :presentations, dependent: :destroy

  # VALIDATIONS
  ############################################################

  validates :code, presence: true, length: { maximum: 50 }
  validates :name, presence: true, length: { maximum: 100 }
  validates :year, presence: true, length: { maximum: 4 }
  validates :description, length: { maximum: 255 }

  # SCOPES
  ############################################################

  scope :not_archived, -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }

  scope :search, ->(search) { where("LOWER(code) LIKE :search OR LOWER(name) LIKE :search", search: "%#{search.downcase}%") }

  # HOOKS
  ############################################################

  before_validation do
    self.name = capitalize_first_char(name) if name.present?
    self.code = code.upcase if code.present?
  end

  before_validation on: :create do
    self.code = Project.default_code if code.blank?
  end

  # be sure archived projects are not in users prefer
  after_save do
    if archived
      Users::Prefer.where(
        resource_type: "Project",
        resource_id: id
      ).destroy_all
    end
  end

  # save events
  after_save do
    if saved_change_to_name?
      projects_events.create!(
        message: "Il nome del progetto è stato modificato in \"#{name}\"."
      )
    end

    if saved_change_to_archived?
      projects_events.create!(
        message: "Il progetto è stato #{archived ? 'archiviato' : 'riattivato'}."
      )
    end
  end

  # cache updates
  after_save_commit do
    tasks.each do |task|
      task.cached_project_name(true)
    end
    procedures.each do |procedure|
      procedure.cached_project_name(true)
    end
    procedures_as_item.each do |procedure|
      procedure.cached_project_items(true)
    end
    cached_percentage_budget_used(true)
  end
  after_destroy_commit do
    procedures.each do |procedure|
      procedure.cached_project_name(true)
    end
    procedures_as_item.each do |procedure|
      procedure.cached_project_items(true)
    end
    cached_percentage_budget_used(true)
  end

  # slack sync
  before_update :update_name_on_slack, if: :name_changed?
  before_update :archive_on_slack, if: :archived_changed?
  before_update :unarchive_on_slack, if: :archived_changed?
  after_destroy :destroy_on_slack

  # QUESTIONS
  ############################################################

  def member_exists?(user_id)
    projects_members.where(user_id: user_id).exists?
  end

  # HELPERS
  ############################################################

  def name_2chars
    name_2chars = name.gsub(/[^a-zA-Z]/, "")[0..1].upcase
    name_2chars = name_2chars[0] + "X" if name_2chars.length < 2

    name_2chars
  end

  def complete_code
    [ year, code ].join(" - ")
  end

  def description_with_budget
    return description unless budget_management

    budget = "💰 #{budget_money}€ ⏱️ #{track_time_string(budget_time)} 📊 #{budget_money_per_time}€/h"

    "#{budget}\n\n#{description}"
  end

  def complete_code_name
    [ year, code, name ].join(" - ")
  end

  def procedures_valid
    @procedures_valid ||= Procedure.valid_for_projects
  end

  def procedures_valid_as_item
    @procedures_valid_as_item ||= Procedure.valid_for_projects_items.where.not(id: procedures_as_item.pluck(:id))
  end

  def archived_reason_string
    @archived_reason_string ||= Project.archived_reason_string(archived_reason)
  end

  def budget_money_per_time
    return 0 unless budget_management
    return 0 if budget_time.zero?

    (budget_money.to_f / budget_time.to_f * 3600).round(2)
  end

  def color_type
    type = ""
    type = "dark" if archived

    type
  end

  def cached_projects_members_count(reset = false)
    Rails.cache.delete("Project/cached_projects_members_count/#{id}") if reset

    @cached_projects_members_count ||= Rails.cache.fetch("Project/cached_projects_members_count/#{id}", expires_in: 7.days) do
      projects_members.count
    end
  end

  def cached_time_spent(reset = false)
    Rails.cache.delete("Project/cached_time_spent/#{id}") if reset

    @cached_time_spent ||= Rails.cache.fetch("Project/cached_time_spent/#{id}", expires_in: 7.days) do
      tasks.sum(:time_spent)
    end
  end

  def cached_percentage_budget_used(reset = false)
    Rails.cache.delete("Project/cached_percentage_budget_used/#{id}") if reset

    @cached_percentage_budget_used ||= Rails.cache.fetch("Project/cached_percentage_budget_used/#{id}", expires_in: 7.days) do
      return 0 unless budget_management
      return 100 if budget_time.zero?

      tasks_time_spent = tasks.sum(:time_spent)
      return 0 if tasks_time_spent.zero?

      (tasks_time_spent.to_f / budget_time.to_f * 100).round(2)
    end
  end

  def track_time_string(seconds) # From ApplicationHelper.track_time
    seconds_diff = seconds
    hours = seconds_diff / 3600
    seconds_diff -= hours * 3600
    minutes = seconds_diff / 60

    "#{hours.to_s.rjust(2, '0')}h #{minutes.to_s.rjust(2, '0')}m"
  end

  # OPERATIONS
  ############################################################

  def create_on_slack
    service = SlackService.new
    response = service.create_channel(name)
    return unless response

    update_column(:slack_channel_id, response["id"])
  end

  def update_name_on_slack
    return unless slack_channel_id

    service = SlackService.new
    service.rename_channel(slack_channel_id, name)
  end

  def archive_on_slack
    return unless slack_channel_id
    return unless archived

    service = SlackService.new
    service.rename_channel(slack_channel_id, "_archived_#{name}")
  end

  def unarchive_on_slack
    return unless slack_channel_id
    return if archived

    service = SlackService.new
    service.rename_channel(slack_channel_id, name)
  end

  def destroy_on_slack
    return unless slack_channel_id

    service = SlackService.new
    service.rename_channel(slack_channel_id, "_deleted_#{name}")
    service.archive_channel(slack_channel_id)
  end

  # CLASS
  ############################################################

  def self.archived_reason_string(archived_reason)
    return "Altro" if archived_reason == "other"
    return "Completato" if archived_reason == "completed"
    return "Non iniziato" if archived_reason == "not_started"
    return "Bloccato da cliente" if archived_reason == "blocked_by_other"
    return "Bloccato da azienda" if archived_reason == "blocked_by_me"

    "Non definito"
  end

  def self.default_code
    SecureRandom.hex(3).upcase
  end
end

app/models/projects.rb
module Projects
  def self.table_name_prefix
    "projects_"
  end
end

app/views/projects/shared/_card-actions.html.erb
<%

project ||= Project.new

%>

<a class="card-link" href="<%= projects_show_path(id: project.id) %>" data-turbo-frame="_top" data-user-policies-target="item" data-policy="projects_show">Visualizza</a>

app/views/projects/shared/_card-content.html.erb
<%

project ||= Project.new
time_spent = project.cached_time_spent
percentage_budget_used = project.cached_percentage_budget_used
percentage_budget_used_bg = 'success'
percentage_budget_used_bg = 'warning' if percentage_budget_used > 50
percentage_budget_used_bg = 'danger' if percentage_budget_used > 75

badge_type = project.color_type
badge_type = 'primary' if badge_type.blank?

%>

<% if project.budget_management && percentage_budget_used.positive? %>
<div
  class="progress mb-3 bg-<%= badge_type %>"
  role="progressbar"
  data-controller="tooltip"
  data-tooltip="<%= percentage_budget_used %>% del budget utilizzato"
>
  <div class="progress-bar progress-bar-striped bg-<%= percentage_budget_used_bg %>" style="width: <%= percentage_budget_used %>%"></div>
</div>
<% end %>

<% if project.cached_projects_members_count.positive? %>
  <span class="badge bg-<%= badge_type %>"><i class="bi bi-people-fill"></i> <%= project.cached_projects_members_count %> persone coinvolte</span>
<% end %>

<% if time_spent.positive? %>
  <span class="badge bg-<%= badge_type %>"><i class="bi bi-hourglass-split"></i> <%= track_time(time_spent) %></span>
<% end %>

<% if project.slack_channel_id %>
  <a class="badge h-bg-slack" href="https://slack.com/app_redirect?channel=<%= project.slack_channel_id %>" target="_blank">💬 Vai al canale Slack</a>
<% end %>

app/views/projects/shared/_card.html.erb
<%

project ||= Project.new
interactive ||= false

# interactive = false if project.archived # archived projects are always not interactive

%>

<%= render 'shared/card',
  nav_icon_key: 'projects',
  title: project.name,
  subtitle: project.complete_code,
  description: project.description_with_budget,
  description_protected: true,
  type: project.color_type,
  resource_id: interactive && !project.archived ? project.id : nil,
  resource_type: interactive && !project.archived ? 'Project' : nil,
  folders_item: interactive ? (project.cached_folder_item_data || {}) : nil,
  render_actions: 'projects/shared/card-actions',
  render_actions_args: { project: project } do
%>
  <%= render 'projects/shared/card-content', project: project %>
<% end %>

app/views/projects/shared/_form-archive.html.erb
<%

project ||= Project.new

%>

<%= render 'shared/form-errors', item: project %>

<%= form_tag projects_archive_action_path(project), class: 'row', data: { controller: 'form-loading' } do %>

  <div class="col col-12 mb-3">
    <label for="name" class="form-label">Motivo dell'archivio</label>
    <%= select_tag :archived_reason, options_for_select(Project.archived_reasons.map {|key, value| [Project.archived_reason_string(key.to_s), Project.archived_reasons.key(value)]}, project.archived_reason), class: 'form-control' %>
  </div>

  <div class="d-flex justify-content-end">
    <button type="submit" class="btn btn-primary btn-form-submit" data-form-loading-target="submit">Conferma</button>
  </div>
<% end %>

app/views/projects/shared/_form-log.html.erb
<%

project ||= Project.new
log ||= Projects::Log.new

path ||= log.persisted? ? projects_edit_log_action_path(id: project.id, log_id: log.id) : projects_add_log_action_path(project)

%>

<%= render 'shared/form-errors', item: log %>

<%= form_tag path, class: 'row', data: { controller: "#{log.persisted? ? 'form-autosave' : ''} form-loading" } do %>

  <div class="col col-12 col-md-12 col-lg-8 col-xl-9 mb-3">
    <label for="title" class="form-label">Titolo</label>
    <input type="text" class="form-control" id="title" name="title" value="<%= log.title %>" required>
  </div>

  <div class="col col-12 col-md-12 col-lg-4 col-xl-3 mb-3">
    <label for="date" class="form-label">Data di riferimento</label>
    <input type="date" class="form-control" id="date" name="date" value="<%= log.date || Date.today %>" required>
  </div>

  <div class="col col-12 mb-3">
    <%= rich_text_area_tag :content, log.content, class: 'trix-content trix-content--lg' %>
  </div>

  <div class="d-flex justify-content-end align-items-center">
    <% if log.persisted? %>
      <span data-form-autosave-target="updateStatus" class="btn btn-link btn-sm text-muted text-decoration-none d-none"></span>
    <% end %>
    <button type="submit" class="btn btn-primary" data-form-loading-target="submit">Conferma</button>
  </div>
<% end %>

app/views/projects/shared/_form-procedure.html.erb
<%

project ||= Project.new
procedure ||= Procedure.new

%>

<%= render 'shared/form-errors', item: procedure %>

<%= form_tag projects_add_procedure_action_path(project), class: 'row', id: 'projectProceduresForm', data: { controller: 'form-loading' } do %>

  <div class="col col-12 mb-3">
    <label for="procedure_id" class="form-label">Modello di partenza</label>
    <%= select_tag 'procedure_id', options_for_select([''] + project.procedures_valid.map { |u| [u.name, u.id] }, ''), class: 'form-control', onchange: 'projectProcedureFormProcedureCloneChange()', required: true %>
  </div>

  <div class="col col-12 mb-3">
    <label for="name" class="form-label">Nome della board</label>
    <input type="text" class="form-control" id="name" name="name" value="<%= procedure.name %>" required>
  </div>

  <hr>

  <div class="col col-12 mb-3">
    <label for="deadline" class="form-label">Imposta la scadenza dei task a</label>
    <input type="date" class="form-control" id="deadline" name="deadline" value="">
  </div>

  <div class="col col-12 mb-3">
    <label for="user_id" class="form-label">Assegna i task a</label>
    <%= select_tag 'user_id', options_for_select([['NESSUNO', '']] + User.all.order(surname: :asc, name: :asc).map { |u| [u.complete_name, u.id] }, ''), class: 'form-control' %>
  </div>

  <div class="d-flex justify-content-end">
    <button type="submit" class="btn btn-primary btn-form-submit" data-form-loading-target="submit">Conferma</button>
  </div>
<% end %>

<script>
function projectProcedureFormProcedureCloneChange() {
  const form = document.querySelector('#projectProceduresForm')
  const procedureCloneInput = form.querySelector('#procedure_id')
  const nameInput = form.querySelector('#name')

  if (procedureCloneInput.value == '') {
    nameInput.value = ''
  } else {
    nameInput.value = procedureCloneInput.options[procedureCloneInput.selectedIndex].text
  }
}
</script>

app/views/projects/shared/_form-procedures-item.html.erb
<%

project ||= Project.new
procedures_item ||= Procedures::Item.new

%>

<%= render 'shared/form-errors', item: procedures_item %>

<%= form_tag projects_add_procedures_item_action_path(project), class: 'row', data: { controller: 'form-loading' } do %>

  <div class="col col-12 mb-3">
    <label for="procedure_id" class="form-label">Board</label>
    <%= select_tag 'procedure_id', options_for_select(project.procedures_valid_as_item.map { |u| [u.name, u.id] }, procedures_item.procedure_id), class: 'form-control' %>
  </div>

  <div class="d-flex justify-content-end">
    <button type="submit" class="btn btn-primary btn-form-submit" data-form-loading-target="submit">Conferma</button>
  </div>
<% end %>

app/views/projects/shared/_module-attachments-actions.html.erb
<%

project ||= Project.new

%>

<a href="<%= projects_actions_path(type: 'add-attachment', id: project.id) %>" data-turbo-frame="action" class="btn btn-primary w-100" >Aggiungi allegato</a>

app/views/projects/shared/_module-infos-actions.html.erb
<div class="fw-lighter text-muted">
<% if project.archived %>
  Il progetto è stato archiviato per <b><%= project.archived_reason_string.upcase %></b>
<% else %>
  Il progetto è <b>ATTIVO</b> dal <b><%= project.created_at.strftime('%d/%m/%Y') %></b>
<% end %>
</div>

app/views/projects/shared/_module-logs-actions.html.erb
<%

project ||= Project.new

%>

<a href="<%= projects_actions_path(type: 'add-log', id: project.id) %>" data-turbo-frame="action" class="btn btn-primary w-100" >Aggiungi nota</a>

app/views/projects/shared/_module-logs.html.erb
<%

project ||= Project.new

%>

<% if project.projects_logs.length.positive? %>
<ol class="list-group">
  <% project.projects_logs.order(date: :desc, created_at: :desc).each do |log| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div>
        <div class="fw-bold mb-1"><%= log.title %> <%= raw log.shareable? ? '<small class="text-primary"><i class="bi bi-eye-fill"></i></small>' : '' %></div>
        <div class="text-muted" style="font-size: 14px;"><%= log.date.strftime('%d/%m/%Y') %></div>
      </div>
      <div class="ms-3 d-flex">
        <div class="dropdown me-1">
          <button class="btn btn-sm btn-outline" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-three-dots"></i>
          </button>
          <ul class="dropdown-menu">
            <% if log.shareable? %>
              <li>
                <div class="ps-3 pe-3">
                  <%= render 'projects/shared/log-share', log: log, small: 'true' %>
                </div>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%= projects_actions_path(id: project.id, type: 'unshare-log', log_id: log.id) %>" data-turbo-frame="action">Annulla condivisione</a></li>
            <% else %>
              <li><a class="dropdown-item" href="<%= projects_actions_path(id: project.id, type: 'share-log', log_id: log.id) %>" data-turbo-frame="action">Condividi</a></li>
            <% end %>
            <li><a class="dropdown-item" href="<%= projects_actions_path(id: project.id, type: 'edit-log', log_id: log.id) %>" data-turbo-frame="action">Modifica</a></li>
            <li><a class="dropdown-item text-danger" href="<%= projects_actions_path(id: project.id, type: 'remove-log', log_id: log.id) %>" data-turbo-frame="action">Elimina</a></li>
          </ul>
        </div>

        <a href="<%= projects_actions_id_path(id: project.id, type: 'show-log', log_id: log.id) %>" data-turbo-frame="action" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a>
      </div>
    </li>
  <% end %>
</ol>
<% else %>
  <%= render 'shared/placeholder' %>
<% end %>

app/views/projects/shared/_module-presentations.html.erb
<% if project.presentations.length.positive? %>
  <% project.presentations.order(name: :asc).each do |presentation| %>
    <div class="mb-3">
      <%= render 'presentations/shared/card', presentation: presentation %>
    </div>
  <% end %>
<% else %>
  <%= render 'shared/placeholder' %>
<% end %>

app/views/projects/shared/_module-procedures-actions.html.erb
<%

project ||= Project.new

%>

<% if project.procedures_valid.length.positive? %>
<a
  href="<%= projects_actions_path(type: 'add-procedure', id: project.id) %>"
  data-turbo-frame="action"
  class="btn btn-primary w-100"
  data-user-policies-target="item" data-policy="procedures_create"
>Aggiungi board</a>
<% end %>

app/views/projects/shared/_module-procedures.html.erb
<% if project.procedures.length.positive? %>
  <% project.procedures.order(name: :asc).sort_by { |p| p.archived ? 1 : 0 }.each do |procedure| %>
    <div class="mb-3">
      <%= render 'procedures/shared/card', procedure: procedure %>
    </div>
  <% end %>
<% else %>
  <%= render 'shared/placeholder' %>
<% end %>