config/routes.rb
  post "projects/edit-member-action/:id/:member_id", to: "projects#edit_member_action", as: "projects_edit_member_action"
  post "projects/remove-member-action/:id/:member_id", to: "projects#remove_member_action", as: "projects_remove_member_action"
  post "projects/add-log-action/:id", to: "projects#add_log_action", as: "projects_add_log_action"
  post "projects/edit-log-action/:id/:log_id", to: "projects#edit_log_action", as: "projects_edit_log_action"
  post "projects/share-log-action/:id/:log_id", to: "projects#share_log_action", as: "projects_share_log_action"
  post "projects/unshare-log-action/:id/:log_id", to: "projects#unshare_log_action", as: "projects_unshare_log_action"
  post "projects/remove-log-action/:id/:log_id", to: "projects#remove_log_action", as: "projects_remove_log_action"
  post "projects/add-attachment-action/:id", to: "projects#add_attachment_action", as: "projects_add_attachment_action"
  post "projects/edit-attachment-action/:id/:attachment_id", to: "projects#edit_attachment_action", as: "projects_edit_attachment_action"
  post "projects/remove-attachment-action/:id/:attachment_id", to: "projects#remove_attachment_action", as: "projects_remove_attachment_action"
  get "projects/:folder_id", to: "projects#index", as: "projects_for_folder"

  # Procedure
  get "procedures", to: "procedures#index", as: "procedures"
  get "procedures/show/:id", to: "procedures#show", as: "procedures_show"
  get "procedures/actions/:type", to: "procedures#actions", as: "procedures_actions"
  get "procedures/actions/:type/:id", to: "procedures#actions", as: "procedures_actions_id"
  post "procedures/create-action", to: "procedures#create_action", as: "procedures_create_action"
  post "procedures/edit-action/:id", to: "procedures#edit_action", as: "procedures_edit_action"
  post "procedures/archive-action/:id", to: "procedures#archive_action", as: "procedures_archive_action"
  post "procedures/unarchive-action/:id", to: "procedures#unarchive_action", as: "procedures_unarchive_action"
  post "procedures/toggle-show-archived-projects-action/:id", to: "procedures#toggle_show_archived_projects_action", as: "procedures_toggle_show_archived_projects_action"
  post "procedures/remove-archived-projects-action/:id", to: "procedures#remove_archived_projects_action", as: "procedures_remove_archived_projects_action"
  post "procedures/clone-action/:id", to: "procedures#clone_action", as: "procedures_clone_action"
  post "procedures/destroy-action/:id", to: "procedures#destroy_action", as: "procedures_destroy_action"
  post "procedures/add-status-action/:id", to: "procedures#add_status_action", as: "procedures_add_status_action"
  post "procedures/edit-status-action/:id/:status_id", to: "procedures#edit_status_action", as: "procedures_edit_status_action"
  post "procedures/edit-status-assignments-action/:id/:status_id", to: "procedures#edit_status_assignments_action", as: "procedures_edit_status_assignments_action"
  post "procedures/remove-status-action/:id/:status_id", to: "procedures#remove_status_action", as: "procedures_remove_status_action"
  post "procedures/move-status-action/:id/:status_id", to: "procedures#move_status_action", as: "procedures_move_status_action"
  post "procedures/toggle-status-automation-action/:id/:status_id", to: "procedures#toggle_status_automation_action", as: "procedures_toggle_status_automation_action"
  post "procedures/take-tasks-to-status-action/:id/:status_id", to: "procedures#take_tasks_to_status_action", as: "procedures_take_tasks_to_status_action"
  post "procedures/add-item-action/:id", to: "procedures#add_item_action", as: "procedures_add_item_action"
  post "procedures/edit-item-action/:id/:item_id", to: "procedures#edit_item_action", as: "procedures_edit_item_action"
  post "procedures/remove-item-action/:id/:item_id", to: "procedures#remove_item_action", as: "procedures_remove_item_action"
  post "procedures/move-item-action/:id/:item_id", to: "procedures#move_item_action", as: "procedures_move_item_action"

  # Posts
  get "posts", to: "posts#index", as: "posts"
  get "posts/actions/:type", to: "posts#actions", as: "posts_actions"
  post "posts/create-action", to: "posts#create_action", as: "posts_create_action"
  post "posts/edit-action/:id", to: "posts#edit_action", as: "posts_edit_action"
  post "posts/destroy-action/:id", to: "posts#destroy_action", as: "posts_destroy_action"

  # Presentation
  get "presentations", to: "presentations#index", as: "presentations"
  get "presentations/show/:id", to: "presentations#show", as: "presentations_show"
  get "presentations/player/:id", to: "presentations#player", as: "presentations_player"
  get "presentations/actions/:type", to: "presentations#actions", as: "presentations_actions"
  get "presentations/actions/:type/:id", to: "presentations#actions", as: "presentations_actions_id"
  post "presentations/create-action", to: "presentations#create_action", as: "presentations_create_action"
  post "presentations/edit-action/:id", to: "presentations#edit_action", as: "presentations_edit_action"
  post "presentations/import-action/:id", to: "presentations#import_action", as: "presentations_import_action"
  post "presentations/destroy-action/:id", to: "presentations#destroy_action", as: "presentations_destroy_action"
  post "presentations/share-action/:id", to: "presentations#share_action", as: "presentations_share_action"
  post "presentations/unshare-action/:id", to: "presentations#unshare_action", as: "presentations_unshare_action"
  post "presentations/add-page-action/:id", to: "presentations#add_page_action", as: "presentations_add_page_action"
  post "presentations/edit-page-action/:id/:page_id", to: "presentations#edit_page_action", as: "presentations_edit_page_action"
  post "presentations/remove-page-action/:id/:page_id", to: "presentations#remove_page_action", as: "presentations_remove_page_action"
  post "presentations/move-page-action/:id/:page_id", to: "presentations#move_page_action", as: "presentations_move_page_action"
  post "presentations/add-action-action/:id", to: "presentations#add_action_action", as: "presentations_add_action_action"
  post "presentations/remove-action-action/:id", to: "presentations#remove_action_action", as: "presentations_remove_action_action"
  post "presentations/add-note-action/:id", to: "presentations#add_note_action", as: "presentations_add_note_action"
  post "presentations/remove-note-action/:id", to: "presentations#remove_note_action", as: "presentations_remove_note_action"

  # Task
  get "tasks", to: "tasks#index", as: "tasks"
  get "tasks/show/:id", to: "tasks#show", as: "tasks_show"
  get "tasks/actions/:type", to: "tasks#actions", as: "tasks_actions"
  get "tasks/actions/:type/:id", to: "tasks#actions", as: "tasks_actions_id"
  post "tasks/create-action", to: "tasks#create_action", as: "tasks_create_action"
  post "tasks/edit-action/:id", to: "tasks#edit_action", as: "tasks_edit_action"
  post "tasks/destroy-action/:id", to: "tasks#destroy_action", as: "tasks_destroy_action"
  post "tasks/complete-action/:id", to: "tasks#complete_action", as: "tasks_complete_action"
  post "tasks/postpone-action/:id", to: "tasks#postpone_action", as: "tasks_postpone_action"
  post "tasks/uncomplete-action/:id", to: "tasks#uncomplete_action", as: "tasks_uncomplete_action"
  post "tasks/start-track-action/:id", to: "tasks#start_track_action", as: "tasks_start_track_action"
  post "tasks/ping-track-action/:id/:track_id", to: "tasks#ping_track_action", as: "tasks_ping_track_action"
  post "tasks/end-track-action/:id/:track_id", to: "tasks#end_track_action", as: "tasks_end_track_action"
  post "tasks/toggle-check-action/:id/:check_id", to: "tasks#toggle_check_action", as: "tasks_toggle_check_action"
  get "tasks/resume-per-inputdate", to: "tasks#resume_per_inputdate", as: "tasks_resume_per_inputdate"

  # Credentials
  get "credentials", to: "credentials#index", as: "credentials"
  get "credentials/actions/:type", to: "credentials#actions", as: "credentials_actions"
  get "credentials/actions/:type/:id", to: "credentials#actions", as: "credentials_actions_id"
  post "credentials/set-phrase-action", to: "credentials#set_phrase_action", as: "credentials_set_phrase_action"
  post "credentials/create-action", to: "credentials#create_action", as: "credentials_create_action"
  post "credentials/edit-action/:id", to: "credentials#edit_action", as: "credentials_edit_action"
  post "credentials/destroy-action/:id", to: "credentials#destroy_action", as: "credentials_destroy_action"
  get "credentials/:folder_id", to: "credentials#index", as: "credentials_for_folder"

  # Folders
  get "folders/show/:id", to: "folders#show", as: "folders_show"
  get "folders/actions/:type", to: "folders#actions", as: "folders_actions"
  get "folders/actions/:type/:id", to: "folders#actions", as: "folders_actions_id"
  post "folders/create-action", to: "folders#create_action", as: "folders_create_action"
  post "folders/edit-action/:id", to: "folders#edit_action", as: "folders_edit_action"
  post "folders/destroy-action/:id", to: "folders#destroy_action", as: "folders_destroy_action"
  post "folders/manage-resource-action", to: "folders#manage_resource_action", as: "folders_manage_resource_action"

  # Settings
  get "settings", to: "settings#index", as: "settings"
  post "settings/edit-infos-action", to: "settings#edit_infos_action", as: "settings_edit_infos_action"
  post "settings/edit-functionalities-action", to: "settings#edit_functionalities_action", as: "settings_edit_functionalities_action"
  post "settings/edit-vectorsearch-action", to: "settings#edit_vectorsearch_action", as: "settings_edit_vectorsearch_action"
  post "settings/edit-slack-action", to: "settings#edit_slack_action", as: "settings_edit_slack_action"
  post "settings/reset-action", to: "settings#reset_action", as: "settings_reset_action"

  # Tools
  get "tools", to: "tools#index", as: "tools"

app/models/tasks.rb
module Tasks
  def self.table_name_prefix
    "tasks_"
  end
end

app/models/tasks/check.rb
class Tasks::Check < ApplicationRecord
  include Cachable

  # RELATIONS
  ############################################################

  belongs_to :task

  # HOOKS
  ############################################################

  before_create do
    default_order = (task.tasks_checks.pluck(:order).max || 0) + 1
    self.order = default_order
  end
end

app/models/tasks/follower.rb
class Tasks::Follower < ApplicationRecord
  include Cachable

  # RELATIONS
  ############################################################

  belongs_to :user, optional: true
  belongs_to :task
end

app/models/tasks/track.rb
class Tasks::Track < ApplicationRecord
  include Cachable

  # VALIDATIONS
  ############################################################

  validates :start_at, presence: true

  # RELATIONS
  ############################################################

  belongs_to :user, optional: true
  belongs_to :task

  # SCOPES
  ############################################################

  scope :not_closed, -> { where(end_at: nil) }
  scope :closed, -> { where.not(end_at: nil) }

  # HOOKS
  ############################################################

  before_validation on: :create do
    self.start_at = Time.now if start_at.nil? || start_at > Time.now
    self.ping_at = start_at
  end

  # cache updates
  after_save_commit do
    task.project&.cached_time_spent(true)
    task.project&.cached_percentage_budget_used(true)
  end
  after_destroy_commit do
    task.project&.cached_time_spent(true)
    task.project&.cached_percentage_budget_used(true)
  end

  # HELPERS
  ############################################################

  def duration
    return ping_at - start_at unless end_at

    end_at - start_at
  end

  # OPERATIONS
  ############################################################

  def close(with_time_limit = false)
    unless end_at.nil?
      errors.add(:base, "Track già chiuso")
      return
    end

    if with_time_limit && ping_at >= 10.minutes.ago
      errors.add(:base, "Track non ancora concluso")
      return
    end

    ActiveRecord::Base.transaction do
      time_to_close = Time.now
      if with_time_limit
        return true unless ping_at < 10.minutes.ago # do not close if last ping is too recent
        time_to_close = ping_at + 15.seconds
      end

      # set time_to_close to be at minimum 5 minutes after start_at
      time_to_close = [ time_to_close, start_at + 5.minutes ].max

      # run updates
      update!(end_at: time_to_close)
      task.update_columns(time_spent: (task.time_spent || 0) + duration)
      update_columns(time_spent: duration)
    end

    true
  rescue StandardError => e
    Rails.logger.error e
    errors.add(:base, e.message)
    false
  end
end

app/views/tasks/_calendar-filters.html.erb
<%

date_start ||= Date.today
date_end ||= Date.today
user_id ||= nil
project_id ||= nil

%>

<div class="d-flex justify-content-between align-items-center mb-4">
  <div>
    <h2 class="fs-4 mb-0"><%= date_start.strftime('%d/%m') %> - <%= date_end.strftime('%d/%m') %></h2>
  </div>
  <form class="row g-3" method="GET">
    <div class="col-auto d-none d-lg-block" style="width: 150px">
      <label for="project_id" class="visually-hidden">Project</label>
      <%= select_tag 'project_id', options_for_select([['Progetto', '']] + Project.not_archived.order(year: :asc, name: :asc).map { |u| [u.name, u.id] }, project_id), class: 'form-control' %>
    </div>
    <div class="col-auto d-none d-lg-block" style="width: 150px">
      <label for="user_id" class="visually-hidden">User</label>
      <%= select_tag 'user_id', options_for_select([['Assegnati a', '']] + User.all.order(surname: :asc, name: :asc).map { |u| [u.complete_name, u.id] }, user_id), class: 'form-control' %>
    </div>
    <div class="col-auto d-none d-lg-block">
      <label for="date_start" class="visually-hidden">Date start</label>
      <input type="date" class="form-control" id="date_start" name="date_start" placeholder="Date start" value="<%= date_start %>" required data-controller="tasks-inputdate">
    </div>
    <div class="col-auto d-none d-lg-block">
      <label for="date_end" class="visually-hidden">Date end</label>
      <input type="date" class="form-control" id="date_end" name="date_end" placeholder="Date end" value="<%= date_end %>" required data-controller="tasks-inputdate">
    </div>
    <div class="col-auto">
      <%= link_to tasks_path(date_start: date_start.at_beginning_of_week - 7.days, date_end: date_start.at_beginning_of_week - 1.days, user_id: user_id, project_id: project_id), class: 'btn btn-primary' do %>
        <i class="bi bi-arrow-left"></i>
      <% end %>
      <%= link_to tasks_path(date_start: date_start.at_beginning_of_week + 7.days, date_end: date_start.at_beginning_of_week + 13.days, user_id: user_id, project_id: project_id), class: 'btn btn-primary' do %>
        <i class="bi bi-arrow-right"></i>
      <% end %>
      <button type="submit" class="btn btn-primary d-none d-lg-inline-block">Applica</button>
    </div>
  </form>
</div>

app/views/tasks/_calendar-item.html.erb
<%

task ||= Task.new
turbo_frame_key = dom_id(task, 'tasks-calendar-item')


%>

<%= turbo_frame_tag turbo_frame_key do %>
  <li class="c-kanban__item list-group-item">
    <%= render 'tasks/shared/card', task: task, turbo_frame_key: 'tasks-calendar' %>
  </li>
<% end %>

app/views/tasks/_calendar-status.html.erb
<%

date ||= Date.today
tasks ||= []
turbo_frame_key = "tasks-calendar-status-#{date.strftime("%Y-%m-%d")}"

time_estimate_sum = tasks.sum(&:time_estimate)
time_spent_sum = tasks.sum(&:time_spent)

%>

<%= turbo_frame_tag turbo_frame_key do %>
  <div class="c-kanban__status card d-flex flex-direction-column justify-content-between me-3">
    <div class="c-kanban__status-header card-header d-flex align-items-center justify-content-between border-bottom-0 rounded-bottom">
      <div class="h-text-oneline">
        <%= raw "<b>#{l(date, format: '%a').capitalize}</b> <small class='#{date == Date.today ? 'text-dark fw-bold' : 'text-muted'}'>#{date.strftime('%d/%m/%Y')}</small>" %>
      </div>
      <div class="ms-3 d-flex align-items-center gap-1">
        <% if date <= Date.today %>
          <span
            class="badge rounded-pill text-white bg-primary"
            style="font-size: 10px;"
            data-controller="tooltip"
            data-tooltip="Tempo consumato"
          >
            <i class="bi bi-hourglass-split"></i>
            <%= track_time time_spent_sum %>
          </span>
        <% end %>
        <span
          class="badge rounded-pill text-white bg-<%= tasks_time_estimate_color(tasks) %>"
          style="font-size: 10px;"
          data-controller="tooltip"
          data-tooltip="Tempo stimato"
        >
          <i class="bi bi-alarm-fill"></i>
          <%= track_time time_estimate_sum %>
        </span>
        <span
          class="badge rounded-pill text-white <%= tasks.length.positive? ? 'bg-info' : 'bg-dark' %>"
          style="font-size: 10px;"
        >
          <%= tasks.select(&:completed).length %> / <%= tasks.length %>
        </span>
      </div>
    </div>
    <ul class="list-group list-group-flush h-fullscroll">
      <% if tasks.length.positive? %>
        <% tasks.sort_by { |t| t.title.downcase }.sort_by { |t| t.completed ? 1 : 0 }.each do |task| %>
          <%= render 'tasks/calendar-item', task: task %>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_calendar.html.erb
<%

date_start ||= Date.today
date_end ||= Date.today
tasks_per_date ||= {}

%>

<%= turbo_frame_tag 'tasks-calendar' do %>
  <div
    class="c-kanban"
  >
    <div class="c-kanban__prev"><i class="bi bi-arrow-left-circle"></i></div>
    <div class="c-kanban__scrollable">
      <% (date_start..date_end).each do |date| %>
        <%= render 'tasks/calendar-status', date: date, tasks: tasks_per_date[date] %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tasks/_index-actions.html.erb
<div class="btn-group" role="group">
  <% if @mode == 'people' %>
    <a
      type="button"
      class="btn btn-primary"
      href="<%= tasks_path(mode: 'calendar') %>"
      data-turbo-frame="_top"
      data-controller="tooltip"
      data-tooltip="Vista calendario"
    >
      <i class="bi bi-calendar"></i>
    </a>
  <% else %>
    <a
      type="button"
      class="btn btn-primary"
      href="<%= tasks_path(mode: 'people') %>"
      data-turbo-frame="_top"
      data-controller="tooltip"
      data-tooltip="Vista persone"
    >
      <i class="bi bi-person"></i>
    </a>
  <% end %>

  <a
    type="button"
    class="btn btn-primary"
    href="<%= tasks_actions_path(type: 'create', turbo_frame_key: "tasks-#{@mode}") %>"
    data-turbo-frame="action"
    data-user-policies-target="item"
    data-policy="tasks_create"
    data-controller="tooltip"
    data-tooltip="Crea nuovo task"
  >
    <i class="bi bi-plus-circle"></i>
  </a>
</div>

app/views/tasks/_people-filters.html.erb
<%

date ||= Date.today
project_id ||= nil

%>

<div class="d-flex justify-content-between align-items-center mb-4">
  <div>
    <h2 class="fs-4 mb-0"><%= date.strftime('%d/%m') %></h2>
  </div>
  <form class="row g-3" method="GET">
    <input type="hidden" name="mode" value="people">

    <div class="col-auto d-none d-lg-block" style="width: 150px">
      <label for="project_id" class="visually-hidden">Project</label>
      <%= select_tag 'project_id', options_for_select([['Progetto', '']] + Project.not_archived.order(year: :asc, name: :asc).map { |u| [u.name, u.id] }, project_id), class: 'form-control' %>
    </div>
    <div class="col-auto d-none d-lg-block">
      <label for="date" class="visually-hidden">Date</label>
      <input type="date" class="form-control" id="date" name="date" placeholder="Date" value="<%= date %>" required data-controller="tasks-inputdate">
    </div>
    <div class="col-auto">
      <%= link_to tasks_path(date: date - 1.days, project_id: project_id, mode: 'people'), class: 'btn btn-primary' do %>
        <i class="bi bi-arrow-left"></i>
      <% end %>
      <%= link_to tasks_path(date: date + 1.days, project_id: project_id, mode: 'people'), class: 'btn btn-primary' do %>
        <i class="bi bi-arrow-right"></i>
      <% end %>
      <button type="submit" class="btn btn-primary d-none d-lg-inline-block">Applica</button>
    </div>
  </form>
</div>

app/views/tasks/_people-item.html.erb
<%

task ||= Task.new
turbo_frame_key = dom_id(task, 'tasks-people-item')

%>

<%= turbo_frame_tag turbo_frame_key do %>
  <li class="c-kanban__item list-group-item">
    <%= render 'tasks/shared/card', task: task, turbo_frame_key: 'tasks-people' %>
  </li>
<% end %>

app/views/tasks/_people-status.html.erb
<%

user ||= User.new
tasks ||= []
turbo_frame_key = "tasks-people-status-#{user.id}"

total_time_sum = tasks.sum(&:time_estimate)

%>

<%= turbo_frame_tag turbo_frame_key do %>
  <div class="c-kanban__status card d-flex flex-direction-column justify-content-between me-3">
    <div class="c-kanban__status-header card-header d-flex align-items-center justify-content-between border-bottom-0 rounded-bottom">
      <div class="h-text-oneline">
        <%= user.complete_name.blank? ? 'Non assegnato' : user.complete_name %>
      </div>
      <div class="ms-3">
        <span
          class="badge rounded-pill text-white bg-<%= tasks_time_estimate_color(tasks) %>"
        >
          <%= track_time total_time_sum %>
        </span>
        <span
          class="badge rounded-pill text-white <%= tasks.length.positive? ? 'bg-info' : 'bg-dark' %>"
        >
          <%= tasks.select(&:completed).length %> / <%= tasks.length %>
        </span>
      </div>
    </div>
    <ul class="list-group list-group-flush h-fullscroll">
      <% if tasks.length.positive? %>
        <% tasks.sort_by { |t| t.completed ? 1 : 0 }.each do |task| %>
          <%= render 'tasks/people-item', task: task %>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_people.html.erb
<%

tasks_per_user ||= {}
users = User.where(id: tasks_per_user.keys).order(:surname, :name)

%>

<%= turbo_frame_tag 'tasks-people' do %>
  <% if users.length.positive? %>
    <div
      class="c-kanban"
    >
      <div class="c-kanban__prev"><i class="bi bi-arrow-left-circle"></i></div>
      <div class="c-kanban__scrollable">
        <% users.each do |user| %>
          <%= render 'tasks/people-status', user: user, tasks: tasks_per_user[user.id] %>
        <% end %>
        <% if tasks_per_user[nil] %>
          <%= render 'tasks/people-status', tasks: tasks_per_user[nil] %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="text-center pt-5 pb-5">
      <%= render 'shared/placeholder' %>
    </div>
  <% end %>
<% end %>

app/views/tasks/_show-actions.html.erb
<div class="btn-group" role="group">
  <a
    type="button"
    href="<%= tasks_actions_path(type: 'edit', id: @task.id) %>"
    data-turbo-frame="action"
    class="btn btn-primary"
    data-user-policies-target="item"
    data-policy="tasks_edit"
    data-controller="tooltip"
    data-tooltip="Modifica"
  ><i class="bi bi-pencil"></i></a>
  <% if @task.completed %>
    <a
      type="button"
      href="<%= tasks_actions_path(type: 'uncomplete', id: @task.id) %>"
      data-turbo-frame="action"
      class="btn btn-warning"
      data-user-policies-target="item"
      data-policy="tasks_uncomplete"
      data-controller="tooltip"
      data-tooltip="Riattiva"
    ><i class="bi bi-x-circle"></i></a>
  <% elsif @task.accepted %>
    <a
      type="button"
      href="<%= tasks_actions_path(type: 'complete', id: @task.id) %>"
      data-turbo-frame="action"
      class="btn btn-success"
      data-user-policies-target="item"
      data-policy="tasks_complete"
      data-controller="tooltip"
      data-tooltip="Completa"
    ><i class="bi bi-check-circle"></i></a>
  <% end %>
  <a
    type="button"
    href="<%= tasks_actions_path(type: 'destroy', id: @task.id) %>"
    data-turbo-frame="action"
    class="btn btn-danger"
    data-user-policies-target="item"
    data-policy="tasks_destroy"
    data-controller="tooltip"
    data-tooltip="Elimina"
  ><i class="bi bi-trash"></i></a>
</div>

app/views/tasks/_tracker.html.erb
<%

track = @session_user.active_tasks_track

%>

<%= turbo_frame_tag 'tasks-tracker' do %>
  <% if track %>
  <div
    class="c-tasks-tracker"
    data-controller="tasks-tracker"
    data-tasks-tracker-start-value="<%= track.start_at.to_i %>"
    data-tasks-tracker-pingpath-value="<%= tasks_ping_track_action_path(id: track.task_id, track_id: track.id) %>"
  >
    <div class="c-tasks-tracker__container">
      <div
        class="c-tasks-tracker__title"
        data-controller="tooltip"
        data-tooltip="<%= track.task.title %>"
      >
        <span class="point bg-<%= track.task.color_type %>"></span>
        <span><%= track.task.title.truncate(30) %></span>
      </div>
      <div class="c-tasks-tracker__time" data-tasks-tracker-target="time"></div>
      <div class="c-tasks-tracker__actions">
        <a
          href="<%= tasks_actions_path(type: 'show', id: track.task.id) %>"
          data-tasks-tracker-target="ctaShow"
          data-turbo-frame="action"
          data-controller="tooltip"
          data-tooltip="Visualizza"
        ><i class="bi bi-info-circle-fill"></i></a>
        <a
          href="<%= tasks_end_track_action_path(id: track.task.id, track_id: track.id) %>"
          data-turbo-method="post"
          data-turbo-frame="tasks-tracker"
          data-controller="tooltip"
          data-tooltip="Ferma tracking"
        ><i class="bi bi-stop-circle-fill"></i></a>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/tasks/index.html.erb
<%= render 'shared/page-header', title: 'Task - calendario', render_actions: 'tasks/index-actions' %>

<%= render 'tasks/calendar-filters', date_start: @date_start, date_end: @date_end, user_id: @user_id, project_id: @project_id %>

<%= render 'tasks/calendar', date_start: @date_start, date_end: @date_end, tasks_per_date: @tasks_per_date %>

app/views/tasks/index_people.html.erb
<%= render 'shared/page-header', title: 'Task - persone', render_actions: 'tasks/index-actions' %>

<%= render 'tasks/people-filters', date: @date, project_id: @project_id %>

<%= render 'tasks/people', date: @date, tasks_per_user: @tasks_per_user %>

app/views/tasks/show.html.erb
<%= render 'shared/page-header',
  title: @task.title,
  render_actions: 'tasks/show-actions',
  back: true
%>

<%= render 'shared/page-grid' do %>

  <%= render 'shared/page-grid-item' do %>

    <%= render 'shared/page-card',
      title: "Dettagli",
      always_open: true,
      render_content: 'tasks/shared/module-infos',
      render_content_args: {
        task: @task
      },
      render_footer: 'tasks/shared/module-infos-actions',
      render_footer_args: {
        task: @task
      }
    %>

  <% end %>

  <%= render 'shared/page-grid-item' do %>

    <%= render 'shared/page-card',
      title: "Relazioni",
      render_content: 'tasks/shared/module-relations',
      render_content_args: {
        task: @task
      }
    %>

  <% end %>

  <% unless @task.tasks_checks.empty? %>
    <%= render 'shared/page-grid-item' do %>

      <%= render 'shared/page-card',
        title: "Checklist",
        render_content: 'tasks/shared/module-checks',
        render_content_args: {
          task: @task
        }
      %>

    <% end %>
  <% end %>

<% end %>