config/routes.rb
Rails.application.routes.draw do
  root "application#index"
  get "service-worker.js", to: "application#serviceworker", as: "serviceworker"
  get "/up", to: "application#up", as: "up"
  get "cacheclear", to: "application#cacheclear", as: "cacheclear"
  get "jobsrun", to: "application#jobsrun", as: "jobsrun"

  # Authentication
  get "authentication/login", to: "authentication#login", as: "authentication_login"
  get "authentication/recover-password", to: "authentication#recover_password", as: "authentication_recover_password"
  get "authentication/update-password/:id", to: "authentication#update_password", as: "authentication_update_password"
  post "authentication/login-action", to: "authentication#login_action", as: "authentication_login_action"
  post "authentication/recover-password-action", to: "authentication#recover_password_action", as: "authentication_recover_password_action"
  post "authentication/update-password-action/:id", to: "authentication#update_password_action", as: "authentication_update_password_action"
  get "authentication/logout", to: "authentication#logout", as: "authentication_logout"
  get "authentication/first-run", to: "authentication#first_run", as: "authentication_first_run"
  post "authentication/first-run-action", to: "authentication#first_run_action", as: "authentication_first_run_action"

  # User
  get "users", to: "users#index", as: "users"
  get "users/show/:id", to: "users#show", as: "users_show"
  get "users/actions/:type", to: "users#actions", as: "users_actions"
  get "users/actions/:type/:id", to: "users#actions", as: "users_actions_id"
  post "users/create-action", to: "users#create_action", as: "users_create_action"
  post "users/edit-action/:id", to: "users#edit_action", as: "users_edit_action"
  post "users/edit-policies-action/:id", to: "users#edit_policies_action", as: "users_edit_policies_action"
  post "users/regenerate-password-action/:id", to: "users#regenerate_password_action", as: "users_regenerate_password_action"
  post "users/destroy-action/:id", to: "users#destroy_action", as: "users_destroy_action"
  post "users/toggle-prefer-action", to: "users#toggle_prefer_action", as: "users_toggle_prefer_action"

  # Project
  get "projects", to: "projects#index", as: "projects"
  get "projects/show/:id", to: "projects#show", as: "projects_show"
  get "projects/show-attachment/:id", to: "projects#show_attachment", as: "projects_show_attachment"
  get "projects/show-log/:id", to: "projects#show_log", as: "projects_show_log"
  get "projects/actions/:type", to: "projects#actions", as: "projects_actions"
  get "projects/actions/:type/:id", to: "projects#actions", as: "projects_actions_id"
  post "projects/create-action", to: "projects#create_action", as: "projects_create_action"
  post "projects/edit-action/:id", to: "projects#edit_action", as: "projects_edit_action"
  post "projects/archive-action/:id", to: "projects#archive_action", as: "projects_archive_action"
  post "projects/unarchive-action/:id", to: "projects#unarchive_action", as: "projects_unarchive_action"
  post "projects/destroy-action/:id", to: "projects#destroy_action", as: "projects_destroy_action"
  post "projects/add-procedure-action/:id", to: "projects#add_procedure_action", as: "projects_add_procedure_action"
  post "projects/add-procedures-item-action/:id", to: "projects#add_procedures_item_action", as: "projects_add_procedures_item_action"
  post "projects/add-member-action/:id", to: "projects#add_member_action", as: "projects_add_member_action"
  post "projects/edit-member-action/:id/:member_id", to: "projects#edit_member_action", as: "projects_edit_member_action"
  post "projects/remove-member-action/:id/:member_id", to: "projects#remove_member_action", as: "projects_remove_member_action"
  post "projects/add-log-action/:id", to: "projects#add_log_action", as: "projects_add_log_action"
  post "projects/edit-log-action/:id/:log_id", to: "projects#edit_log_action", as: "projects_edit_log_action"
  post "projects/share-log-action/:id/:log_id", to: "projects#share_log_action", as: "projects_share_log_action"
  post "projects/unshare-log-action/:id/:log_id", to: "projects#unshare_log_action", as: "projects_unshare_log_action"
  post "projects/remove-log-action/:id/:log_id", to: "projects#remove_log_action", as: "projects_remove_log_action"
  post "projects/add-attachment-action/:id", to: "projects#add_attachment_action", as: "projects_add_attachment_action"
  post "projects/edit-attachment-action/:id/:attachment_id", to: "projects#edit_attachment_action", as: "projects_edit_attachment_action"
  post "projects/remove-attachment-action/:id/:attachment_id", to: "projects#remove_attachment_action", as: "projects_remove_attachment_action"
  get "projects/:folder_id", to: "projects#index", as: "projects_for_folder"

  # Procedure
  get "procedures", to: "procedures#index", as: "procedures"
  get "procedures/show/:id", to: "procedures#show", as: "procedures_show"
  get "procedures/actions/:type", to: "procedures#actions", as: "procedures_actions"
  get "procedures/actions/:type/:id", to: "procedures#actions", as: "procedures_actions_id"
  post "procedures/create-action", to: "procedures#create_action", as: "procedures_create_action"
  post "procedures/edit-action/:id", to: "procedures#edit_action", as: "procedures_edit_action"
  post "procedures/archive-action/:id", to: "procedures#archive_action", as: "procedures_archive_action"
  post "procedures/unarchive-action/:id", to: "procedures#unarchive_action", as: "procedures_unarchive_action"
  post "procedures/toggle-show-archived-projects-action/:id", to: "procedures#toggle_show_archived_projects_action", as: "procedures_toggle_show_archived_projects_action"
  post "procedures/remove-archived-projects-action/:id", to: "procedures#remove_archived_projects_action", as: "procedures_remove_archived_projects_action"
  post "procedures/clone-action/:id", to: "procedures#clone_action", as: "procedures_clone_action"
  post "procedures/destroy-action/:id", to: "procedures#destroy_action", as: "procedures_destroy_action"
  post "procedures/add-status-action/:id", to: "procedures#add_status_action", as: "procedures_add_status_action"
  post "procedures/edit-status-action/:id/:status_id", to: "procedures#edit_status_action", as: "procedures_edit_status_action"
  post "procedures/edit-status-assignments-action/:id/:status_id", to: "procedures#edit_status_assignments_action", as: "procedures_edit_status_assignments_action"
  post "procedures/remove-status-action/:id/:status_id", to: "procedures#remove_status_action", as: "procedures_remove_status_action"
  post "procedures/move-status-action/:id/:status_id", to: "procedures#move_status_action", as: "procedures_move_status_action"
  post "procedures/toggle-status-automation-action/:id/:status_id", to: "procedures#toggle_status_automation_action", as: "procedures_toggle_status_automation_action"
  post "procedures/take-tasks-to-status-action/:id/:status_id", to: "procedures#take_tasks_to_status_action", as: "procedures_take_tasks_to_status_action"
  post "procedures/add-item-action/:id", to: "procedures#add_item_action", as: "procedures_add_item_action"
  post "procedures/edit-item-action/:id/:item_id", to: "procedures#edit_item_action", as: "procedures_edit_item_action"
  post "procedures/remove-item-action/:id/:item_id", to: "procedures#remove_item_action", as: "procedures_remove_item_action"
  post "procedures/move-item-action/:id/:item_id", to: "procedures#move_item_action", as: "procedures_move_item_action"

  # Posts
  get "posts", to: "posts#index", as: "posts"
  get "posts/actions/:type", to: "posts#actions", as: "posts_actions"
  post "posts/create-action", to: "posts#create_action", as: "posts_create_action"
  post "posts/edit-action/:id", to: "posts#edit_action", as: "posts_edit_action"
  post "posts/destroy-action/:id", to: "posts#destroy_action", as: "posts_destroy_action"

  # Presentation
  get "presentations", to: "presentations#index", as: "presentations"
  get "presentations/show/:id", to: "presentations#show", as: "presentations_show"
  get "presentations/player/:id", to: "presentations#player", as: "presentations_player"
  get "presentations/actions/:type", to: "presentations#actions", as: "presentations_actions"
  get "presentations/actions/:type/:id", to: "presentations#actions", as: "presentations_actions_id"
  post "presentations/create-action", to: "presentations#create_action", as: "presentations_create_action"
  post "presentations/edit-action/:id", to: "presentations#edit_action", as: "presentations_edit_action"
  post "presentations/import-action/:id", to: "presentations#import_action", as: "presentations_import_action"
  post "presentations/destroy-action/:id", to: "presentations#destroy_action", as: "presentations_destroy_action"
  post "presentations/share-action/:id", to: "presentations#share_action", as: "presentations_share_action"
  post "presentations/unshare-action/:id", to: "presentations#unshare_action", as: "presentations_unshare_action"
  post "presentations/add-page-action/:id", to: "presentations#add_page_action", as: "presentations_add_page_action"
  post "presentations/edit-page-action/:id/:page_id", to: "presentations#edit_page_action", as: "presentations_edit_page_action"
  post "presentations/remove-page-action/:id/:page_id", to: "presentations#remove_page_action", as: "presentations_remove_page_action"
  post "presentations/move-page-action/:id/:page_id", to: "presentations#move_page_action", as: "presentations_move_page_action"
  post "presentations/add-action-action/:id", to: "presentations#add_action_action", as: "presentations_add_action_action"
  post "presentations/remove-action-action/:id", to: "presentations#remove_action_action", as: "presentations_remove_action_action"
  post "presentations/add-note-action/:id", to: "presentations#add_note_action", as: "presentations_add_note_action"

app/models/users.rb
module Users
  def self.table_name_prefix
    "users_"
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# UsersController.
class UsersController < ApplicationController
  before_action :validate_session_user!
  before_action do
    @_navbar = "users"
  end
  before_action :user_finder_for_show, only: :show

  caches_action :index, cache_path: -> { current_cache_action_path }, layout: false
  def index
    return unless validate_policy!("users_index")

    query = User.all
    query = query.where("LOWER(name) LIKE :search OR LOWER(surname) LIKE :search OR LOWER(email) LIKE :search", search: "%#{params[:search].downcase}%") unless params[:search].blank?
    query = query.order(surname: :asc, name: :asc)
    @users = paginate_query(query)
  end

  caches_action :show, cache_path: -> { current_cache_action_path }, layout: false
  def show
    return unless @_is_dashboard || validate_policy!("users_show")

    # load general data
    @projects = @user.projects_as_member.not_archived.order(name: :asc).sort_by { |p| p.user_prefer?(@session_user)  ? -1 : 1 }
    @tasks = @user.tasks.not_completed.includes(:project, :procedures_as_item).order(deadline: :asc, alghoritmic_order: :asc, title: :asc)
    @tasks = @tasks.where(project_id: params[:tasks_project_id]) if params[:tasks_project_id]
    @tasks_projects = Project.joins(:tasks).where(tasks: { user_id: @user.id, completed: false }).includes(folders_item: :folder).select("projects.*, COUNT(tasks.id) AS _total_tasks").group("projects.id").sort_by { |p| p._total_tasks }.reverse
    @tasks_followed = Task.joins(:tasks_followers).where(tasks_followers: { user_id: @user.id }).not_completed.order(deadline: :asc, alghoritmic_order: :asc, title: :asc)

    # manage search
    if params[:search] && params[:search].length >= 3
      @search = params[:search]
      @search_results = {}
      @search_results[:projects] = Project.not_archived.search(params[:search]).order(name: :asc).limit(25).load_async
      @search_results[:credentials] = Credential.search(params[:search]).order(name: :asc).limit(25).load_async
      @search_results[:tasks] = Task.not_completed.search(params[:search]).order(deadline: :asc, alghoritmic_order: :asc, title: :asc).limit(25).load_async
      @search_results[:procedures] = Procedure.not_as_model.not_archived.search(params[:search]).where(projects: { archived: [ nil, false ] }).order(name: :asc).limit(25).load_async
      @search_results[:projects_archived] = Project.archived.search(params[:search]).order(name: :asc).limit(25).load_async

      if @search_results[:projects].count.positive? || @search_results[:credentials].count.positive? || @search_results[:tasks].count.positive? || @search_results[:procedures].count.positive?
        @session_user.log_search(@search)
      end
    end
  end

  caches_action :actions, cache_path: -> { current_cache_action_path }, layout: false
  def actions
    @type = params[:type]
    @user = params[:id].present? ? User.find(params[:id]) : User.new

    return render "users/actions/create" if @type == "create"
    return render "users/actions/edit" if @type == "edit"
    return render "users/actions/edit_policies" if @type == "edit-policies"
    return render "users/actions/regenerate_password" if @type == "regenerate-password"
    return render "users/actions/destroy" if @type == "destroy"

    render partial: "shared/action-error"
  end

  def create_action
    return unless validate_policy!("users_create")

    password = SecureRandom.hex(8).upcase
    @user = User.new(user_params.merge(password: password, password_confirmation: password))
    return render "users/actions/create" unless @user.save

    render partial: "shared/action-feedback", locals: {
      title: "Nuovo utente",
      turbo_frame: "page-index",
      feedback_args: {
        title: "Utente creato",
        subtitle: "L'utente #{@user.complete_name} è stato creato con successo. La sua password di accesso è <b>#{password}</b>.",
        render_content: "users/shared/card",
        render_content_args: { user: @user },
        type: "success"
      }
    }
  end

  def edit_action
    return unless validate_policy!("users_edit")
    return unless user_finder

    return render "users/actions/edit" unless @user.update(user_params)

    render partial: "shared/action-feedback", locals: {
      title: "Modifica profilo",
      turbo_frame: "page-header",
      feedback_args: {
        title: "Profilo aggiornato",
        subtitle: "Il profilo di #{@user.complete_name} è stato aggiornato con successo.",
        render_content: "users/shared/card",
        render_content_args: { user: @user },
        type: "success"
      }
    }
  end

  def edit_policies_action
    return unless validate_policy!("users_edit_policies")
    return unless user_finder

    return render "users/actions/edit" unless @user.update_policies(params.permit(policies: [])[:policies])

    render partial: "shared/action-feedback", locals: {
      title: "Modifica permessi",
      turbo_frame: "page-header",
      feedback_args: {
        title: "Permessi utente aggiornati",
        subtitle: "I permessi di #{@user.complete_name} sono stati aggiornati con successo.",
        type: "success"
      }
    }
  end

  def destroy_action
    return unless validate_policy!("users_destroy")
    return unless user_finder

    @user.destroy

    render partial: "shared/action-feedback", locals: {
      title: "Elimina utente",
      turbo_frame: "_top",
      feedback_args: {
        title: "Utente eliminato",
        subtitle: "L'utente #{@user.complete_name} è stato eliminato e non potrà più accedere.",
        type: "success"
      }
    }
  end

  def regenerate_password_action
    return unless validate_policy!("users_edit_password")
    return unless user_finder

    password = SecureRandom.hex(8).upcase
    @user.update(password: password, password_confirmation: password)

    render partial: "shared/action-feedback", locals: {
      title: "Rigenera password",
      turbo_frame: "_top",
      feedback_args: {
        title: "Password rigenerata",
        subtitle: "La password di #{@user.complete_name} è stata rigenerata con successo. La nuova password è <b>#{password}</b>.",
        type: "success"
      }
    }
  end

  # PREFERS
  ################################################################################

  def toggle_prefer_action
    prefer = @session_user.users_prefers.find_by(resource_id: params[:resource_id], resource_type: params[:resource_type])
    if prefer
      prefer.destroy

      render partial: "shared/action-feedback", locals: {
        title: "Rimuovi preferito",
        turbo_frame: "_top",
        feedback_args: {
          title: "Preferito rimosso",
          subtitle: "Hai tolto il preferito.",
          type: "success"
        }
      }
    else
      @session_user.users_prefers.create(resource_id: params[:resource_id], resource_type: params[:resource_type])

      render partial: "shared/action-feedback", locals: {
        title: "Aggiungi preferito",
        turbo_frame: "_top",
        feedback_args: {
          title: "Preferito aggiunto",
          subtitle: "Hai aggiunto il preferito.",
          type: "success"
        }
      }
    end
  end

  private

  def user_params
    params.permit(:name, :surname, :email, :image_profile)
  end

  def user_finder
    return true if @user

    # HACK: Save a query
    if @session_user_id == params[:id]&.to_i
      @user = @session_user
      return true
    end

    @user = User.find_by(id: params[:id])
    unless @user
      flash[:danger] = "Utente non trovato"
      redirect_to users_path
      return false
    end

    true
  end

  def user_finder_for_show
    return unless user_finder

    @_is_dashboard = @user.id == @session_user_id
    @_navbar = "dashboard" if @_is_dashboard
  end
end

app/views/users/shared/_card-actions.html.erb
<%

user ||= User.new

%>

<a class="card-link" href="<%= users_show_path(id: user.id) %>" data-turbo-frame="_top" data-user-policies-target="item" data-policy="users_show">
  Visualizza
</a>

app/views/users/shared/_card.html.erb
<%

user ||= User.new

title = ""
title += "<img src=\"#{user.image_profile.attached? ? url_for(user.image_profile_thumb) : '/statics/placeholder-profile.jpg'}\" style=\"width: 35px; height: 35px;\" class=\"rounded-circle border border-primary border-2 me-1\">"
title += "<span class=\"align-middle\"> #{user.complete_name} </span>"

%>

<%= render 'shared/card',
  nav_icon_key: 'users',
  title: title,
  subtitle: user.email,
  render_actions: 'users/shared/card-actions',
  render_actions_args: { user: user } %>

app/views/users/shared/_form-policies.html.erb
<%

user ||= User.new

%>

<%= render 'shared/form-errors', item: user %>

<%= form_tag users_edit_policies_action_path(user), class: 'row', data: { controller: 'user-policies-form form-loading' } do %>

  <div class="col col-12 mb-3">
    <label for="preset" class="form-label">Preset</label>
    <%= select_tag :preset, options_for_select([
      [],
      ['Amministratore', 'admin'],
      ['Produzione interno', 'production_internal'],
      ['Produzione esterno', 'production_external']
    ]), class: 'form-control', data: { user_policies_form_target: 'preset' } %>
  </div>

  <div class="col col-12 mb-3">
    <label for="policies" class="form-label">Permessi</label>
    <%= select_tag :policies, options_for_select(Users::Policy.policies.keys.map { |k| [k.humanize, k] }, user.cached_policies), class: 'form-control', multiple: true, style: 'height: 300px;', data: { user_policies_form_target: 'policies' } %>
  </div>

  <div class="d-flex justify-content-end">
    <button type="submit" class="btn btn-primary btn-form-submit" data-form-loading-target="submit">Conferma</button>
  </div>
<% end %>

app/views/users/shared/_form.html.erb
<%

user ||= User.new

path ||= user.persisted? ? users_edit_action_path(user) : users_create_action_path


%>

<%= render 'shared/form-errors', item: user %>

<%= form_tag path, class: 'c-modal-form', multipart: true, data: { controller: 'form-loading' } do %>
  <div class="c-modal-form__fields row">
    <div class="col col-12 mb-3">
      <label for="name" class="form-label">Nome</label>
      <input type="text" class="form-control" id="name" name="name" value="<%= user.name %>" required>
    </div>
    <div class="col col-12 mb-3">
      <label for="surname" class="form-label">Cognome</label>
      <input type="text" class="form-control" id="surname" name="surname" value="<%= user.surname %>" required>
    </div>
    <div class="col col-12 mb-3">
      <label for="email" class="form-label">Email</label>
      <input type="email" class="form-control" id="email" name="email" value="<%= user.email %>" required>
    </div>

    <div class="col col-12 mb-3">
      <div class="row">
        <div class="col col-auto mb-3">
          <img src="<%= user.image_profile.attached? ? url_for(user.image_profile_thumb) : '/statics/placeholder-profile.jpg' %>" style="width: 100px; height: 100px; object-fit: cover;" class="img-thumbnail">
        </div>
        <div class="col mb-3">
          <label for="image_profile" class="form-label">Immagine di profilo</label>
          <input type="file" class="form-control" id="image_profile" name="image_profile">
          <div class="form-text">Sono accettati i formati .jpg e .png</div>
        </div>
      </div>
    </div>
  </div>

  <div class="c-modal-form__submit">
    <button type="submit" class="btn btn-primary btn-form-submit" data-form-loading-target="submit">Conferma</button>
  </div>
<% end %>

app/views/users/shared/_module-credentials.html.erb
<%

credentials ||= []

%>

<div class="row">
  <% credentials.each do |credential| %>
    <div class="col col-12 col-xl-4 mb-3">
      <%= render 'credentials/shared/card', credential: credential, show_only: true %>
    </div>
  <% end %>
</div>

app/views/users/shared/_module-projects-actions.html.erb
<a href="<%= projects_path %>" data-turbo-frame="_top" class="btn btn-primary w-100" data-user-policies-target="item" data-policy="projects_index">Vai ai progetti</a>

app/views/users/shared/_module-projects.html.erb
<%= turbo_frame_tag 'module-projects' do %>

<% if projects.length.positive? %>
  <% projects.each do |project| %>
    <div class="mb-3">
      <%= render 'projects/shared/card-interactive', project: project %>
    </div>
  <% end %>
<% else %>
  <%= render 'shared/placeholder' %>
<% end %>

<% end %>

app/views/users/shared/_module-search.html.erb
<%

projects ||= []
search ||= ''
search_results ||= {}
search_has_results = false

%>

<%= turbo_frame_tag 'module-search' do %>

  <div class="pt-1 pb-2 border-bottom" style="position: sticky; top: -16px; z-index: 1; background-color: rgba(255,255,255,0.95);">
    <%= form_tag '', method: :get, class: 'd-flex', data: { turbo_frame: 'module-search-results', controller: 'filters' } do %>
      <div class="input-group">
        <input type="text" name="search" list="moduleSearchSuggestions" class="form-control" placeholder="Ricerca" value="<%= search %>" aria-label="Ricerca" data-filters-target="inputToClear" data-action="keyup->filters#submitDebounced" autofocus>
        <button class="btn btn-light border" type="button" data-action="click->filters#clear"><i class="bi bi-x-circle"></i></button>
        <button class="btn btn-primary" data-filters-target="submit" type="submit"><i class="bi bi-search"></i></button>
      </div>
      <datalist id="moduleSearchSuggestions">
        <% @session_user.cached_users_logs_search_values.each do |log_value| %>
          <option value="<%= log_value %>"><%= log_value %></option>
        <% end %>
      </datalist>
    <% end %>
  </div>

  <div class="mt-3">
    <%= turbo_frame_tag 'module-search-results' do %>
      <% if search_results[:projects]&.length&.positive? %>
        <% search_has_results = true %>
        <div class="mb-3 d-flex justify-content-between align-items-center">
          <h4>Progetti</h4>
          <span
            class="badge text-bg-primary rounded-pill"
            data-controller="tooltip"
            data-tooltip="Ci sono <%= search_results[:projects].length %> progetti attivi che corrispondono alla ricerca"
          ><%= search_results[:projects].length %></span>
        </div>
        <% search_results[:projects].each do |project| %>
          <div class="mb-3">
            <%= render 'projects/shared/card', project: project %>
          </div>
        <% end %>
        <hr>
      <% end %>

      <% if search_results[:credentials]&.length&.positive? %>
        <% search_has_results = true %>
        <div class="mb-3 d-flex justify-content-between align-items-center">
          <h4>Credenziali</h4>
          <span
            class="badge text-bg-primary rounded-pill"
            data-controller="tooltip"
            data-tooltip="Ci sono <%= search_results[:credentials].length %> credenziali che corrispondono alla ricerca"
          ><%= search_results[:credentials].length %></span>
        </div>
        <% search_results[:credentials].each do |credential| %>
          <div class="mb-3">
            <%= render 'credentials/shared/card', credential: credential %>
          </div>
        <% end %>
        <hr>
      <% end %>

      <% if search_results[:tasks]&.length&.positive? %>
        <% search_has_results = true %>
        <div class="mb-3 d-flex justify-content-between align-items-center">
          <h4>Task</h4>
          <span
            class="badge text-bg-primary rounded-pill"
            data-controller="tooltip"
            data-tooltip="Ci sono <%= search_results[:tasks].length %> task che corrispondono alla ricerca"
          ><%= search_results[:tasks].length %></span>
        </div>
        <% search_results[:tasks].each do |task| %>
          <div class="mb-3">
            <%= render 'tasks/shared/card', task: task %>
          </div>
        <% end %>
        <hr>
      <% end %>

      <% if search_results[:procedures]&.length&.positive? %>
        <% search_has_results = true %>
        <div class="mb-3 d-flex justify-content-between align-items-center">
          <h4>Board</h4>
          <span
            class="badge text-bg-primary rounded-pill"
            data-controller="tooltip"
            data-tooltip="Ci sono <%= search_results[:procedures].length %> board trovate."
          ><%= search_results[:procedures].length %></span>
        </div>
        <% search_results[:procedures].each do |procedure| %>
          <div class="mb-3">
            <%= render 'procedures/shared/card', procedure: procedure %>
          </div>
        <% end %>
        <hr>
      <% end %>

      <% if search_results[:projects_archived]&.length&.positive? %>
        <% search_has_results = true %>
        <div class="mb-3 d-flex justify-content-between align-items-center">
          <h4>Progetti archiviati</h4>
          <span
            class="badge text-bg-primary rounded-pill"
            data-controller="tooltip"
            data-tooltip="Ci sono <%= search_results[:projects_archived].length %> progetti archiviati che corrispondono alla ricerca"
          ><%= search_results[:projects_archived].length %></span>
        </div>
        <% search_results[:projects_archived].each do |project| %>
          <div class="mb-3">
            <%= render 'projects/shared/card', project: project %>
          </div>
        <% end %>
        <hr>
      <% end %>

      <% if search.blank? && !search_has_results %>

        <% if (@session_user.policy?('projects_index') || @session_user.policy?('tasks_index') || @session_user.policy?('procedures_index') || @session_user.policy?('credentials_index')) %>
          <div class="d-flex justify-content-between align-items-center mb-3 pb-3 border-bottom">
            <h6 class="me-2 mb-0 mt-0 text-muted">Shortcuts</h6>
            <div class="d-flex justify-content-start align-items-center">
              <a
                href="<%= tasks_path %>"
                class="btn btn-primary me-1"
                data-turbo-frame="_top"
                data-controller="tooltip"
                data-tooltip="Task"
                data-user-policies-target="item"
                data-policy="tasks_index"
              >
                <%= nav_icon('tasks') %>
              </a>
              <a
                href="<%= projects_path %>"
                class="btn btn-primary me-1"
                data-turbo-frame="_top"
                data-controller="tooltip"
                data-tooltip="Progetti"
                data-user-policies-target="item"
                data-policy="projects_index"
              >
                <%= nav_icon('projects') %>
              </a>
              <a
                href="<%= procedures_path %>"
                class="btn btn-primary me-1"
                data-turbo-frame="_top"
                data-controller="tooltip"
                data-tooltip="Board"
                data-user-policies-target="item"
                data-policy="procedures_index"
              >
                <%= nav_icon('procedures') %>
              </a>
              <a
                href="<%= credentials_path %>"
                class="btn btn-primary me-1"
                data-turbo-frame="_top"
                data-controller="tooltip"
                data-tooltip="Credenziali"
                data-user-policies-target="item"
                data-policy="credentials_index"
              >
                <%= nav_icon('credentials') %>
              </a>
            </div>
          </div>
        <% end %>

        <div class="mb-3 d-flex justify-content-between align-items-center">
          <h4>Progetti attivi</h4>
          <span
            class="badge text-bg-primary rounded-pill"
            data-controller="tooltip"
            data-tooltip="Ci sono <%= projects.length %> progetti attivi registrati"
          ><%= projects.length %></span>
        </div>
        <% projects.each do |project| %>
          <div class="mb-3">
            <%= render 'projects/shared/card-interactive', project: project %>
          </div>
        <% end %>
      <% elsif !search_has_results %>
        <%= render 'shared/placeholder', message: 'Nessun risultato disponibile' %>
      <% end %>
    <% end %>
  </div>

<% end %>

app/views/users/shared/_module-tasks-actions.html.erb
<a href="<%= tasks_actions_path(type: 'create', turbo_frame_key: 'module-tasks-assigned') %>" data-turbo-frame="action" class="btn btn-primary w-100" data-user-policies-target="item" data-policy="tasks_create">Aggiungi task</a>

app/views/users/shared/_preview.html.erb
<%

user_id ||= nil
size ||= nil
type ||= 'primary'

style = 'width: 1.5em; height: 1.5em; object-fit: cover; margin-right: 0.1em; position: relative; top: -0.15em;'
style = 'width: 2em; height: 2em; object-fit: cover; margin-right: 0.2em; position: relative; top: -0.15em;' if size == 'lg'

data = User.cached_preview_data(user_id)

%>

<span class="align-middle">
<img src="<%= data[:image_profile_url] %>" style="<%= style %>" class="rounded-circle border border-<%= type %> border-2">
<%= data[:complete_name]  %>
</span>