config/routes.rb
Rails.application.routes.draw do
  root "application#index"
  get "service-worker.js", to: "application#serviceworker", as: "serviceworker"
  get "/up", to: "application#up", as: "up"
  get "cacheclear", to: "application#cacheclear", as: "cacheclear"
  get "jobsrun", to: "application#jobsrun", as: "jobsrun"

  # Authentication
  get "authentication/login", to: "authentication#login", as: "authentication_login"
  get "authentication/recover-password", to: "authentication#recover_password", as: "authentication_recover_password"
  get "authentication/update-password/:id", to: "authentication#update_password", as: "authentication_update_password"
  post "authentication/login-action", to: "authentication#login_action", as: "authentication_login_action"
  post "authentication/recover-password-action", to: "authentication#recover_password_action", as: "authentication_recover_password_action"
  post "authentication/update-password-action/:id", to: "authentication#update_password_action", as: "authentication_update_password_action"
  get "authentication/logout", to: "authentication#logout", as: "authentication_logout"
  get "authentication/first-run", to: "authentication#first_run", as: "authentication_first_run"
  post "authentication/first-run-action", to: "authentication#first_run_action", as: "authentication_first_run_action"

  # User
  get "users", to: "users#index", as: "users"
  get "users/show/:id", to: "users#show", as: "users_show"
  get "users/actions/:type", to: "users#actions", as: "users_actions"
  get "users/actions/:type/:id", to: "users#actions", as: "users_actions_id"
  post "users/create-action", to: "users#create_action", as: "users_create_action"
  post "users/edit-action/:id", to: "users#edit_action", as: "users_edit_action"
  post "users/edit-policies-action/:id", to: "users#edit_policies_action", as: "users_edit_policies_action"
  post "users/regenerate-password-action/:id", to: "users#regenerate_password_action", as: "users_regenerate_password_action"
  post "users/destroy-action/:id", to: "users#destroy_action", as: "users_destroy_action"
  post "users/toggle-prefer-action", to: "users#toggle_prefer_action", as: "users_toggle_prefer_action"

  # Project
  get "projects", to: "projects#index", as: "projects"
  get "projects/show/:id", to: "projects#show", as: "projects_show"
  get "projects/show-attachment/:id", to: "projects#show_attachment", as: "projects_show_attachment"
  get "projects/show-log/:id", to: "projects#show_log", as: "projects_show_log"
  get "projects/actions/:type", to: "projects#actions", as: "projects_actions"
  get "projects/actions/:type/:id", to: "projects#actions", as: "projects_actions_id"
  post "projects/create-action", to: "projects#create_action", as: "projects_create_action"
  post "projects/edit-action/:id", to: "projects#edit_action", as: "projects_edit_action"
  post "projects/archive-action/:id", to: "projects#archive_action", as: "projects_archive_action"
  post "projects/unarchive-action/:id", to: "projects#unarchive_action", as: "projects_unarchive_action"
  post "projects/destroy-action/:id", to: "projects#destroy_action", as: "projects_destroy_action"
  post "projects/add-procedure-action/:id", to: "projects#add_procedure_action", as: "projects_add_procedure_action"
  post "projects/add-procedures-item-action/:id", to: "projects#add_procedures_item_action", as: "projects_add_procedures_item_action"
  post "projects/add-member-action/:id", to: "projects#add_member_action", as: "projects_add_member_action"
  post "projects/edit-member-action/:id/:member_id", to: "projects#edit_member_action", as: "projects_edit_member_action"
  post "projects/remove-member-action/:id/:member_id", to: "projects#remove_member_action", as: "projects_remove_member_action"
  post "projects/add-log-action/:id", to: "projects#add_log_action", as: "projects_add_log_action"
  post "projects/edit-log-action/:id/:log_id", to: "projects#edit_log_action", as: "projects_edit_log_action"
  post "projects/share-log-action/:id/:log_id", to: "projects#share_log_action", as: "projects_share_log_action"
  post "projects/unshare-log-action/:id/:log_id", to: "projects#unshare_log_action", as: "projects_unshare_log_action"
  post "projects/remove-log-action/:id/:log_id", to: "projects#remove_log_action", as: "projects_remove_log_action"
  post "projects/add-attachment-action/:id", to: "projects#add_attachment_action", as: "projects_add_attachment_action"
  post "projects/edit-attachment-action/:id/:attachment_id", to: "projects#edit_attachment_action", as: "projects_edit_attachment_action"
  post "projects/remove-attachment-action/:id/:attachment_id", to: "projects#remove_attachment_action", as: "projects_remove_attachment_action"
  get "projects/:folder_id", to: "projects#index", as: "projects_for_folder"

  # Procedure
  get "procedures", to: "procedures#index", as: "procedures"
  get "procedures/show/:id", to: "procedures#show", as: "procedures_show"
  get "procedures/actions/:type", to: "procedures#actions", as: "procedures_actions"
  get "procedures/actions/:type/:id", to: "procedures#actions", as: "procedures_actions_id"
  post "procedures/create-action", to: "procedures#create_action", as: "procedures_create_action"
  post "procedures/edit-action/:id", to: "procedures#edit_action", as: "procedures_edit_action"
  post "procedures/archive-action/:id", to: "procedures#archive_action", as: "procedures_archive_action"
  post "procedures/unarchive-action/:id", to: "procedures#unarchive_action", as: "procedures_unarchive_action"
  post "procedures/toggle-show-archived-projects-action/:id", to: "procedures#toggle_show_archived_projects_action", as: "procedures_toggle_show_archived_projects_action"
  post "procedures/remove-archived-projects-action/:id", to: "procedures#remove_archived_projects_action", as: "procedures_remove_archived_projects_action"
  post "procedures/clone-action/:id", to: "procedures#clone_action", as: "procedures_clone_action"
  post "procedures/destroy-action/:id", to: "procedures#destroy_action", as: "procedures_destroy_action"
  post "procedures/add-status-action/:id", to: "procedures#add_status_action", as: "procedures_add_status_action"
  post "procedures/edit-status-action/:id/:status_id", to: "procedures#edit_status_action", as: "procedures_edit_status_action"
  post "procedures/edit-status-assignments-action/:id/:status_id", to: "procedures#edit_status_assignments_action", as: "procedures_edit_status_assignments_action"
  post "procedures/remove-status-action/:id/:status_id", to: "procedures#remove_status_action", as: "procedures_remove_status_action"
  post "procedures/move-status-action/:id/:status_id", to: "procedures#move_status_action", as: "procedures_move_status_action"
  post "procedures/toggle-status-automation-action/:id/:status_id", to: "procedures#toggle_status_automation_action", as: "procedures_toggle_status_automation_action"
  post "procedures/take-tasks-to-status-action/:id/:status_id", to: "procedures#take_tasks_to_status_action", as: "procedures_take_tasks_to_status_action"
  post "procedures/add-item-action/:id", to: "procedures#add_item_action", as: "procedures_add_item_action"
  post "procedures/edit-item-action/:id/:item_id", to: "procedures#edit_item_action", as: "procedures_edit_item_action"
  post "procedures/remove-item-action/:id/:item_id", to: "procedures#remove_item_action", as: "procedures_remove_item_action"
  post "procedures/move-item-action/:id/:item_id", to: "procedures#move_item_action", as: "procedures_move_item_action"

  # Posts
  get "posts", to: "posts#index", as: "posts"
  get "posts/actions/:type", to: "posts#actions", as: "posts_actions"
  post "posts/create-action", to: "posts#create_action", as: "posts_create_action"
  post "posts/edit-action/:id", to: "posts#edit_action", as: "posts_edit_action"
  post "posts/destroy-action/:id", to: "posts#destroy_action", as: "posts_destroy_action"

  # Presentation
  get "presentations", to: "presentations#index", as: "presentations"
  get "presentations/show/:id", to: "presentations#show", as: "presentations_show"
  get "presentations/player/:id", to: "presentations#player", as: "presentations_player"
  get "presentations/actions/:type", to: "presentations#actions", as: "presentations_actions"
  get "presentations/actions/:type/:id", to: "presentations#actions", as: "presentations_actions_id"
  post "presentations/create-action", to: "presentations#create_action", as: "presentations_create_action"
  post "presentations/edit-action/:id", to: "presentations#edit_action", as: "presentations_edit_action"
  post "presentations/import-action/:id", to: "presentations#import_action", as: "presentations_import_action"
  post "presentations/destroy-action/:id", to: "presentations#destroy_action", as: "presentations_destroy_action"
  post "presentations/share-action/:id", to: "presentations#share_action", as: "presentations_share_action"
  post "presentations/unshare-action/:id", to: "presentations#unshare_action", as: "presentations_unshare_action"
  post "presentations/add-page-action/:id", to: "presentations#add_page_action", as: "presentations_add_page_action"
  post "presentations/edit-page-action/:id/:page_id", to: "presentations#edit_page_action", as: "presentations_edit_page_action"
  post "presentations/remove-page-action/:id/:page_id", to: "presentations#remove_page_action", as: "presentations_remove_page_action"
  post "presentations/move-page-action/:id/:page_id", to: "presentations#move_page_action", as: "presentations_move_page_action"
  post "presentations/add-action-action/:id", to: "presentations#add_action_action", as: "presentations_add_action_action"
  post "presentations/remove-action-action/:id", to: "presentations#remove_action_action", as: "presentations_remove_action_action"
  post "presentations/add-note-action/:id", to: "presentations#add_note_action", as: "presentations_add_note_action"

app/models/procedure.rb
class Procedure < ApplicationRecord
  include ActionView::RecordIdentifier
  include Cachable
  include UserPreferrable

  # HACK: to work on ToolsController.projects_tasks_tracking
  attr_accessor :time_spent

  enum :resources_type, {
    projects: 1,
    tasks: 2
  }

  # RELATIONS
  ############################################################

  has_many :procedures_statuses, dependent: :destroy, class_name: "Procedures::Status"

  has_many :procedures_items, dependent: :destroy, class_name: "Procedures::Item"
  has_many :projects_items, through: :procedures_items, source: :resource, source_type: "Project", class_name: "Project"
  has_many :tasks_items, through: :procedures_items, source: :resource, source_type: "Task", class_name: "Task"

  belongs_to :project, optional: true

  # VALIDATIONS
  ############################################################

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 255 }

  # SCOPES
  ############################################################

  scope :not_archived, -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }
  scope :not_as_model, -> { where(model: false) }
  scope :as_model, -> { where(model: true) }

  scope :resources_type_projects, -> { where(resources_type: "projects") }
  scope :resources_type_tasks, -> { where(resources_type: "tasks") }

  scope :search, ->(search) { left_joins(:project).where("LOWER(procedures.name) LIKE :search OR LOWER(projects.code) LIKE :search OR LOWER(projects.name) LIKE :search", search: "%#{search.downcase}%") }

  # ritorna le board che possono essere usate per creare board interni di progetto
  scope :valid_for_projects, -> { not_archived.as_model.where(resources_type: "tasks") }
  # ritorna le board che possono essere usate per creare board esterni di progetto
  scope :valid_for_projects_items, -> { not_archived.not_as_model.resources_type_projects.where("statuses_count > 0") }

  # HOOKS
  ############################################################

  before_validation do
    self.name = capitalize_first_char(name) if name.present?
  end

  # be sure archived procedures are not in users prefer
  after_save do
    Users::Prefer.where(resource_type: "Procedure", resource_id: id).destroy_all if archived
  end

  # update kanban when "show_archived_projects" change
  after_update do
    if saved_change_to_show_archived_projects?
      update_on_turbo_stream_kanban
    end
  end

  # QUESTIONS
  ############################################################

  def resources_type_projects?
    resources_type == "projects"
  end

  def resources_type_tasks?
    resources_type == "tasks"
  end

  def archivable?
    !model
  end

  def clonable?
    project_id.nil?
  end

  # HELPERS
  ############################################################

  def resources_type_string
    @resources_type_string ||= Procedure.resources_type_string(resources_type)
  end

  def resources_items_string
    @resources_items_string ||= Procedure.resources_items_string(resources_type)
  end

  def resources_item_string
    @resources_item_string ||= Procedure.resources_item_string(resources_type)
  end

  def color_type
    type = ""
    type = "secondary" if model
    type = "dark" if archived
    type = "light" if resources_type_projects?

    type
  end

  def cached_project_items(reset = false)
    Rails.cache.delete("Procedure/cached_project_items/#{id}") if reset

    @cached_project_items ||= Rails.cache.fetch("Procedure/cached_project_items/#{id}", expires_in: 7.days) do
      projects_items.order(:name).map do |project|
        {
          id: project.id,
          name: project.name
        }
      end
    end
  end

  def cached_project_name(reset = false)
    Rails.cache.delete("Procedure/cached_project_name/#{id}") if reset

    return "" unless project_id

    @cached_project_name ||= Rails.cache.fetch("Procedure/cached_project_name/#{id}", expires_in: 7.days) do
      project.name
    end
  end

  def cached_task_items_expired_count(reset = false)
    Rails.cache.delete("Procedure/cached_task_items_expired_count/#{id}") if reset

    @cached_task_items_expired_count ||= Rails.cache.fetch("Procedure/cached_task_items_expired_count/#{id}", expires_in: 7.days) do
      tasks_items.not_completed.expired.count
    end
  end

  def cached_task_items_not_completed_count(reset = false)
    Rails.cache.delete("Procedure/cached_task_items_not_completed_count/#{id}") if reset

    @cached_task_items_not_completed_count ||= Rails.cache.fetch("Procedure/cached_task_items_not_completed_count/#{id}", expires_in: 7.days) do
      tasks_items.not_completed.not_expired.count
    end
  end

  def cached_task_items_completed_count(reset = false)
    Rails.cache.delete("Procedure/cached_task_items_completed_count/#{id}") if reset

    @cached_task_items_completed_count ||= Rails.cache.fetch("Procedure/cached_task_items_completed_count/#{id}", expires_in: 7.days) do
      tasks_items.completed.count
    end
  end

  # OPERATIONS
  ############################################################

  def clone(procedure_to_clone, new_name = nil, tasks_data = {})
    ActiveRecord::Base.transaction do
      self.name = new_name || "#{procedure_to_clone.name} (clone)"
      self.resources_type = procedure_to_clone.resources_type
      self.archived = false
      self.model = false
      self.items_count = 0
      self.statuses_count = 0
      save!

      # copy each status of the procedure
      procedure_to_clone.procedures_statuses.each do |status|
        new_status = status.dup
        new_status.procedure = self
        new_status.items_count = 0
        new_status.save!
        new_status.update_column(:order, status.order)

        # copy each automation of the status
        status.procedures_status_automations.each do |automation|
          new_automation = automation.dup
          new_automation.procedures_status = new_status
          new_automation.save!
        end

        # copy each item of the status
        status.procedures_items.each do |item|
          if procedure_to_clone.model && procedure_to_clone.resources_type_projects?
            next
          elsif !procedure_to_clone.model && procedure_to_clone.resources_type_tasks?
            next
          else
            new_item = item.dup
            new_item.procedures_status = new_status
            new_item.procedure = self
            new_item.model_data = nil
            if procedure_to_clone.model && procedure_to_clone.resources_type_tasks?
              p = item.model_data
              tasks_data.each do |k, v|
                next if v.blank?
                p[k] = v
              end
              new_item.resource_id = Task.create(p)&.id
            end

            new_item.save!
          end
        end
      end
    end

    true
  rescue StandardError => e
    Rails.logger.error e
    errors.add(:base, e.message)
    false
  end

  def update_on_turbo_stream_kanban
    broadcast_replace_to dom_id(self), target: dom_id(self, "kanban"), partial: "procedures/kanban", locals: { procedure: self }
  end

  # CLASS
  ############################################################

  def self.resources_type_string(resources_type)
    return "Progetti" if resources_type == "projects"
    return "Task" if resources_type == "tasks"

    "Non definito"
  end

  def self.resources_items_string(resources_type)
    return "progetti" if resources_type == "projects"
    return "task" if resources_type == "tasks"

    "elementi"
  end

  def self.resources_item_string(resources_type)
    return "progetto" if resources_type == "projects"
    return "task" if resources_type == "tasks"

    "elemento"
  end
end

app/models/procedures.rb
module Procedures
  def self.table_name_prefix
    "procedures_"
  end
end

app/views/procedures/_index-actions.html.erb
<div class="btn-group" role="group">
  <a
    type="button"
    class="btn btn-primary"
    href="<%= procedures_actions_path(type: 'create') %>"
    data-turbo-frame="action"
    data-user-policies-target="item"
    data-policy="procedures_create"
    data-controller="tooltip"
    data-tooltip="Crea nuova board"
  >
    <i class="bi bi-plus-circle"></i>
  </a>
</div>

app/views/procedures/_kanban-item.html.erb
<%

item ||= Procedure::Item.new
procedure = item.procedure
turbo_frame_status_key ||= nil
turbo_frame_key = dom_id(item, 'kanban-item')


%>

<%= turbo_frame_tag turbo_frame_key, data: { item: item.id } do %>
  <li class="c-kanban__item list-group-item">
    <div class="c-kanban__item-background border-<%= item.resource_color_type %>"></div>
    <div class="c-kanban__item-actions mb-1 d-flex justify-content-between align-items-start">
      <div>
        <span class="c-kanban__item-title"><%= item.secure_title %></span>
      </div>
      <div class="d-flex justify-content-end">
        <div class="dropdown">
          <button class="btn btn-sm btn-outline me-1" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-three-dots"></i>
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="<%= procedures_actions_path(type: 'edit-item', id: procedure.id, item_id: item.id, turbo_frame_key: turbo_frame_key) %>" data-turbo-frame="action">Modifica</a></li>
            <li data-user-policies-target="item" data-policy="procedures_edit"><a class="dropdown-item text-danger" href="<%= procedures_actions_path(type: 'remove-item', id: procedure.id, item_id: item.id, turbo_frame_key: turbo_frame_status_key) %>" data-turbo-frame="action">Elimina</a></li>
          </ul>
        </div>
        <button
          data-user-policies-target="item"
          data-policy="procedures_edit"
          class="btn btn-sm btn-outline-primary kanban_controller-move-button"
          type="button"
        >
          <i class="bi bi-arrows-move kanban_controller-move-button"></i>
        </button>
        <a
          class="d-none kanban_controller-item-updater"
          href="<%= procedures_move_item_action_path(id: procedure.id, item_id: item.id) %>"
          data-turbo-method="post"
          data-turbo-frame="<%= turbo_frame_key %>"
        ></a>
      </div>
    </div>
    <div class="c-kanban__item-card">
      <%= render 'procedures/shared/card-item', item: item, turbo_frame_key: turbo_frame_key %>
    </div>
  </li>
<% end %>

app/views/procedures/_kanban.html.erb
<%

procedure ||= Procedure.new

%>

<%= turbo_stream_from dom_id(procedure) %>

<%= turbo_frame_tag dom_id(procedure, 'kanban') do %>
  <div
    class="c-kanban"
    data-controller="kanban"
    data-kanban-updater-param-container-value="procedures_status_id"
    data-kanban-updater-param-item-value="item_id"
    data-kanban-updater-param-order-value="order"
  >
    <div class="c-kanban__prev" data-kanban-target="prev"><i class="bi bi-arrow-left-circle"></i></div>
    <div data-kanban-target="scrollable" class="c-kanban__scrollable">
      <% procedure.procedures_statuses.order(order: :asc).each do |status| %>
        <%= render 'procedures/kanban-status', status: status %>
      <% end %>
    </div>
    <div class="c-kanban__next" data-kanban-target="next"><i class="bi bi-arrow-right-circle"></i></div>
  </div>
<% end %>

app/views/procedures/_show-actions.html.erb
<%

has_prefer = false
has_prefer = @session_user.prefer?(@procedure.id, @procedure.class.name) if @session_user && @procedure

%>


<div class="d-flex justify-content-center align-items-center">
  <% if has_prefer %>
    <div class="me-2 text-warning" data-controller="tooltip" data-tooltip="Board nei preferiti">
      <i class="bi bi-bookmark-fill"></i>
    </div>
  <% end %>

  <% if @procedure.archived %>
    <div class="me-2 text-dark" data-controller="tooltip" data-tooltip="Board archiviata">
      <i class="bi bi-archive-fill"></i>
    </div>
  <% end %>

  <div class="dropdown me-1">
    <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-three-dots"></i>
    </button>
    <ul class="dropdown-menu">
      <% if has_prefer %>
        <li>
          <a class="dropdown-item" href="<%= users_toggle_prefer_action_path(resource_id: @procedure.id, resource_type: @procedure.class.name) %>" data-turbo-method="post" data-turbo-frame="action">
            Rimuovi dai preferiti
          </a>
        </li>
      <% else %>
        <li>
          <a class="dropdown-item" href="<%= users_toggle_prefer_action_path(resource_id: @procedure.id, resource_type: @procedure.class.name) %>" data-turbo-method="post" data-turbo-frame="action">
            Aggiungi ai preferiti
          </a>
        </li>
      <% end %>

      <% if @procedure.resources_type_projects? && !@procedure.model %>
        <li data-user-policies-target="item" data-policy="procedures_edit">
          <a class="dropdown-item" href="<%= procedures_remove_archived_projects_action_path(id: @procedure.id) %>" data-turbo-frame="_self" data-turbo-method="post">
            Rimuovi progetti archiviati
          </a>
        </li>
        <li data-user-policies-target="item" data-policy="procedures_edit">
          <a class="dropdown-item" href="<%= procedures_toggle_show_archived_projects_action_path(id: @procedure.id) %>" data-turbo-frame="_self" data-turbo-method="post">
            <% if @procedure.show_archived_projects %>
              Nascondi progetti archiviati
            <% else %>
              Mostra progetti archiviati
            <% end %>
          </a>
        </li>
      <% end %>

      <li data-user-policies-target="item" data-policy="procedures_edit">
        <a class="dropdown-item" href="<%= procedures_actions_path(type: 'edit', id: @procedure.id) %>" data-turbo-frame="action">
          Modifica board
        </a>
      </li>
      <% if @procedure.clonable? %>
        <li data-user-policies-target="item" data-policy="procedures_clone">
          <a class="dropdown-item" href="<%= procedures_actions_path(type: 'clone', id: @procedure.id) %>" data-turbo-frame="action">
            Clona board
          </a>
        </li>
      <% end %>
      <% if @procedure.archivable? %>
        <% if @procedure.archived %>
          <li data-user-policies-target="item" data-policy="procedures_unarchive">
            <a class="dropdown-item" href="<%= procedures_actions_path(type: 'unarchive', id: @procedure.id) %>" data-turbo-frame="action">
              Ri-attiva board
            </a>
          </li>
        <% else %>
          <li data-user-policies-target="item" data-policy="procedures_archive">
            <a class="dropdown-item" href="<%= procedures_actions_path(type: 'archive', id: @procedure.id) %>" data-turbo-frame="action">
              Archivia board
            </a>
          </li>
        <% end %>
      <% end %>
      <li data-user-policies-target="item" data-policy="procedures_destroy">
        <a class="dropdown-item text-danger" href="<%= procedures_actions_path(type: 'destroy', id: @procedure.id) %>" data-turbo-frame="action">
          Elimina board
        </a>
      </li>
    </ul>
  </div>

  <div class="btn-group" role="group">
    <% if !@procedure.model %>
      <a
        type="button"
        href="<%= procedures_actions_path(type: 'search', id: @procedure.id) %>"
        data-turbo-frame="action"
        class="btn btn-primary"
        data-controller="tooltip"
        data-tooltip="Ricerca"
      >
        <i class="bi bi-search"></i>
      </a>
    <% end %>

    <a
      type="button"
      href="<%= procedures_actions_path(type: 'add-status', id: @procedure.id) %>"
      data-turbo-frame="action"
      class="btn btn-primary"
      data-user-policies-target="item"
      data-policy="procedures_edit"
      data-controller="tooltip"
      data-tooltip="Aggiungi stato"
    >
      <i class="bi bi-plus-circle"></i>
    </a>
  </div>
</div>

app/views/procedures/index.html.erb
<%= render 'shared/page-header', title: 'Board', render_actions: 'procedures/index-actions' %>

<%= render 'shared/page-preferred',
    query: @procedures_preferred,
    type: 'Procedure',
    render_item: 'procedures/shared/card',
    render_item_param: :procedure
  %>

<%= render 'shared/page-index',
    query: @procedures,
    render_item: 'procedures/shared/card',
    render_item_param: :procedure,
    search: true,
    filters: [
      { label: 'Attivi', value: 'not-archived', default: true },
      { label: 'Archiviati', value: 'archived' },
      { label: 'Modelli', value: 'model' }
    ]
  %>

app/views/procedures/show.html.erb
<%= render 'shared/page-header',
  title: @procedure.name,
  subtitle: @procedure.project ? link_to(@procedure.project.name, projects_show_path(@procedure.project), data: { turbo_frame: '_top' }) : '',
  render_actions: 'procedures/show-actions',
  back: true
%>

<%= render 'procedures/kanban', procedure: @procedure %>